<?php

namespace DoctrineORMModule\Proxy\__CG__\Transaction\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transaction extends \Transaction\Entity\Transaction implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'user', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'user_plan', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'cycle', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'category_transaction', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'transaction_reference', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'type', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'value', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'date', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'updated_at', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'created_at'];
        }

        return ['__isInitialized__', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'user', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'user_plan', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'cycle', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'category_transaction', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'transaction_reference', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'type', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'value', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'date', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'updated_at', '' . "\0" . 'Transaction\\Entity\\Transaction' . "\0" . 'created_at'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Transaction $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updated_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($created_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPlan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPlan', []);

        return parent::getUserPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPlan($user_plan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPlan', [$user_plan]);

        return parent::setUserPlan($user_plan);
    }

    /**
     * {@inheritDoc}
     */
    public function getCycle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCycle', []);

        return parent::getCycle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCycle($cycle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCycle', [$cycle]);

        return parent::setCycle($cycle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryTransaction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryTransaction', []);

        return parent::getCategoryTransaction();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryTransaction($category_transaction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryTransaction', [$category_transaction]);

        return parent::setCategoryTransaction($category_transaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeStr', []);

        return parent::getTypeStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValue', []);

        return parent::getValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getValueStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValueStr', []);

        return parent::getValueStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setValue($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValue', [$value]);

        return parent::setValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateStr', []);

        return parent::getDateStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionReference', []);

        return parent::getTransactionReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionReference($transaction_reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionReference', [$transaction_reference]);

        return parent::setTransactionReference($transaction_reference);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
