<!DOCTYPE html>
<!-- saved from url=(0024)https://goodbank.com.br/ -->
<html lang="pt-br"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GOODBANK</title>
    <link rel="icon" href="https://goodbank.com.br/favicon.ico" type="image/x-icon">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="/site/bootstrap.min.css">
    <!-- custom css -->
    <link rel="stylesheet" href="/site/main.css">
    <link rel="stylesheet" href="/site/mediaquery.css">
    <link rel="stylesheet" href="/site/themecolor.css">
    <!-- Font icon -->
    <link rel="stylesheet" href="/site/fontawesome-all.css">
    <link rel="stylesheet" href="/site/simple-line-icons.css">
    <!-- Owl carousel -->
    <link rel="stylesheet" href="/site/owl.carousel.min.css">
    <link rel="stylesheet" href="/site/owl.theme.default.min.css">
    <!-- Animate.css -->
    <link href="/site/animate.css" rel="stylesheet" media="all">
    <!-- Magnific Popup core CSS file -->
    <link rel="stylesheet" href="/site/magnific-popup.css">
    <link rel="stylesheet" href="/assets/vendor/icon-awesome/css/font-awesome.min.css">
    <meta name="google-site-verification" content="Xr4KIyPs2-E_gwmpIRGCYE6RHlJvCqt6u0_YCUSSfr0" />
    <!--[if lt IE 9]>

    <![endif]--></head>
<body id="homepage">
<!-- BEGIN PRELOADING -->
<!--<div  class="preloading" style="display: none;">-->
<!--    <div class="wrap-preload">-->
<!--        <div class="loader">-->
<!--            <div class="loader__bar"></div>-->
<!--            <div class="loader__bar"></div>-->
<!--            <div class="loader__bar"></div>-->
<!--            <div class="loader__bar"></div>-->
<!--            <div class="loader__bar"></div>-->
<!--            <div class="loader__ball"></div>-->
<!--        </div>-->
<!--        <div class="text-preloading">CARREGANDO</div>-->
<!--    </div>-->
<!--</div>-->
<?php echo $this->content;?>
<section class="footer">
    <div class="ct-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-footer-box">
                    <div class="row-footer">
                        <div class="logo">
                            <img src="/site/logow.png" alt="logo">
                        </div>
                        <br>
                        <div>
                            Agradecemos pelo reconhecimento e confiança. Nosso crescimento e evolução positiva é resultado não de nossos esforços, mas também pela aplicação e difusão de uma prática empresarial socialmente responsável.<br><br>
                            <br>
                            <div class="footer-sosmed-icon ">
                                <div class="wrap-out-sosdmed-footer">
                                    <div class="wrap-circle-sosmed theme-transition ">
                                        <a href="https://www.instagram.com/goodbankinvestimentos/">
                                            <div class="circle-sosmed">
                                                <i class="fa fa-instagram"></i>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="wrap-out-sosdmed-footer">
                                    <div class="wrap-circle-sosmed theme-transition ">
                                        <a href="https://www.youtube.com/channel/UCcRXVrclUdZI0aR2xlOgQPA">
                                            <div class="circle-sosmed">
                                                <i class="fa fa-youtube"></i>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="wrap-out-sosdmed-footer">
                                    <div class="wrap-circle-sosmed theme-transition ">
                                        <a href="https://www.facebook.com/investimentosgoodbank">
                                            <div class="circle-sosmed">
                                                <i class="fa fa-facebook"></i>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-footer-box">
                    <div class="row-footer">
                        <div class="heading-footer-col">POLÍTICAS</div>
                        <div class="content-footer-col">
                            <ul>
                                <li>
                                    <a href="https://goodbank.com.br/files/home/terms.html" target="_blank">TERMOS DE SERVIÇO</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-footer-box cfb-last">
                    <div class="row-footer">
                        <div class="heading-footer-col">CONTATO</div>
                        <div class="content-footer-col">
                            <div class="footer-item-contact">
                                <div class="fic-icon">
                                    <i class="fa fa-phone"></i>
                                </div>
                                <div class="fic-contact">CONTATO@GOODBANK.COM.BR</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                © 2019 GOODBANK | Todos os direitos reservados
            </div>
        </div>
    </div>
</footer>
<!-- END FOOTER -->

<!-- BACK TO TOP BUTTON -->
<a id="back-to-top" href="https://goodbank.com.br/#" class="btn btn-primary btn-lg back-to-top" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left"><i class="fa fa-arrow-up"></i></a>
<!-- END BACK TO TOP BUTTON -->



<!-- jQuery -->
<script src="/site/jquery-3.3.1.min.js"> </script>
<!-- bootstrap-->
<script src="/site/bootstrap.min.js"> </script>
<!-- stellar -->
<script src="/site/jquery.stellar.js"></script>
<!-- scrollorama js-->
<script src="/site/jquery.scrollorama.js"></script>
<!-- Contact form-->
<script type="text/javascript" src="/site/validator.min.js"></script>
<!--owl carousel -->
<script src="/site/owl.carousel.min.js"></script>
<!-- Inview js -->
<script src="/site/jquery.inview.min.js"> </script>
<!-- Magnific Popup core JS file -->
<script src="/site/jquery.magnific-popup.js"></script>
<!-- Custom js -->
<script src="/site/main.js"> </script>
<script src="/site/coingecko-coin-price-marquee-widget.js"></script>



</body></html>
