<section class="g-bg-gray-light-v5 height-100">
    <div class="container g-py-100">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-lg-5">
                <div class="u-shadow-v21 g-bg-white rounded g-py-40 g-px-30">
                    <header class="text-center mb-4">
                        <img class="img-fluid g-mb-40" src="/assets/logo.png">
                        <h2 class="h2 g-color-black g-font-weight-600">
                            Trocar a senha
                        </h2>
                        <p>Insira seu e-mail, e receba na sua caixa de entrada uma nova senha.</p>
                    </header>
                    <?=$this->getFlashMessenger()?>
                    <form class="form-signin form-validate g-py-15" method="post" action="">
                        <div class="mb-4">
                            <label for="email" class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">
                                Email:
                            </label>
                            <input id="email"
                                   type="email"
                                   name="email"
                                   class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15"
                                   placeholder="Digite o e-mail" required autofocus>
                        </div>
                        <div class="mb-4">
                            <button type="submit" id="login" class="btn btn-md btn-block u-btn-primary rounded g-py-13">
                                RECUPERAR SENHA
                            </button>
                        </div>
                    </form>
                    <footer class="text-center">
                        <div class="row">
                            <div class="col-md-12">
                                <center>
                                    <img style="height: 60px" class="img-fluid" src="/assets/img/certificado-ssl.png">
                                </center>
                            </div>
                        </div>
                        <p class="g-color-gray-dark-v5 g-font-size-13 mb-0">
                            Lembrei minha senha,
                            <a href="<?=$this->url('user-auth')?>" class="g-font-weight-600 color-green-light">
                                <strong>fazer o login</strong>
                            </a>
                        </p>
                    </footer>
                </div>
            </div>
        </div>
    </div>
</section>
