<?php
/**
 * @var \Register\Entity\User $db_sponsor
 */
$db_sponsor = $this->db_sponsor;
?>
<section class="g-bg-gray-light-v5 height-100">
    <div class="container g-py-100">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-lg-5">
                <div class="u-shadow-v21 g-bg-white rounded g-py-40 g-px-30">
                    <header class="text-center mb-4">
                        <img class="img-fluid g-mb-40" src="/assets/logo.png">
                        <h2 class="h2 g-color-black g-font-weight-600">
                            Faça o Cadastro
                        </h2>
                    </header>
                    <?=$this->getFlashMessenger()?>
                    <form class="form-register form-validate g-py-15" method="post" action="">
                        <input type="hidden" name="reference" value="register">
                        <?php
                        if($db_sponsor){
                            ?>
                            <div class="mb-4">
                                <label for="sponsor"
                                       class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">
                                    Patrocinador:
                                </label>
                                <input id="sponsor"
                                       type="text"
                                       style="background-color: #eee !important;"
                                       class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15"
                                       required
                                       readonly
                                       value="<?=$db_sponsor->getName()?>">
                                <input type="hidden" name="sponsor" value="<?=$db_sponsor->getId()?>">
                            </div>
                            <?php
                        }
                        ?>
                        <div class="mb-4">
                            <label for="name"
                                   class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">
                                Nome:
                            </label>
                            <input id="name"
                                   type="text"
                                   name="name"
                                   class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15"
                                   placeholder="Digite seu nome" required autofocus>
                        </div>
                        <div class="mb-4">
                            <label for="email" class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">
                                Email:
                            </label>
                            <input id="email"
                                   type="email"
                                   name="email"
                                   class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15"
                                   placeholder="Digite o e-mail" required autofocus>
                        </div>
                        <div class="g-mb-35">
                            <label for="password" class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">
                                Senha:
                            </label>
                            <input id="password"
                                   type="password"
                                   name="password"
                                   required
                                   data-msg="Por favor entre com a senha"
                                   class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15 mb-3"
                                   placeholder="Digite sua senha">
                        </div>
                        <div class="g-mb-35">
                            <label for="confirmation" class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">
                                Confirme sua senha:
                            </label>
                            <input id="confirmation"
                                   type="password"
                                   name="confirmation"
                                   required
                                   data-msg="Por favor confirme sua senha"
                                   class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15 mb-3"
                                   placeholder="Confirme sua senha">
                        </div>

                        <div class="mb-4">
                            <button type="submit" id="login" class="btn btn-md btn-block u-btn-primary rounded g-py-13">
                                Cadastrar
                            </button>
                        </div>
                    </form>
                    <footer class="text-center">
                        <div class="row">
                            <div class="col-md-12">
                                <center>
                                    <img style="height: 60px" class="img-fluid" src="/assets/img/certificado-ssl.png">
                                </center>
                            </div>
                        </div>
                        <p class="g-color-gray-dark-v5 g-font-size-13 mb-0">
                            Possui uma conta?
                            <a href="<?=$this->url('user-auth')?>" class="g-font-weight-600 color-green-light">
                                <strong>Fazer o Login</strong>
                            </a>
                        </p>
                    </footer>
                </div>
            </div>
        </div>
    </div>
</section>
