<?php

$db_user          = $this->db_user;
$db_roles           = $this->db_roles;
$db_user_roles = $this->db_user_roles;

$arr_roles = array();
if(!empty($db_user_roles))
{
    foreach($db_user_roles as $db_user_role)
    {
        $arr_roles[] = $db_user_role->getRole()->getId();
    }
}

$return = $this->url(
    'user/default',
    array(
        'controller'=>'user'
    )
);

$action = $this->url(
    'user/default',
    array(
        'controller'    =>  'user',
        'action'        =>  'profile',
        'id'            =>  $db_user->getId()
    )
);
?>
<div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20">
    <ul class="u-list-inline g-color-gray-dark-v6">

        <li class="list-inline-item g-mr-10">
            <a class="u-link-v5 g-color-gray-dark-v6 g-color-secondary--hover g-valign-middle"
               href="<?=$this->url('admin');?>">
                Dashboard
            </a>
            <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
        </li>
        <li class="list-inline-item">
            <span class="g-valign-middle">
                Seleção de Perfis
            </span>
        </li>
    </ul>
</div>
<div class="g-pa-20">
    <h1 class="page-title txt-color-blueDark">
        <i class="fa fa-users"></i> Seleção de Perfis <small>- <?=$db_user->getName()?></small>
    </h1>
    <div class="row">
        <div class="col-md-12 mb-4">
            <?php $this->getFlashMessenger();?>
        </div>
    </div>
    <hr class="d-flex g-brd-gray-light-v7 ">
    <div class="col-md-12 g-brd-around g-brd-gray-light-v7 g-rounded-4 g-pa-15 g-pa-20--md g-mb-30">
        <h2 class="g-font-weight-400 g-font-size-20 g-color-black mb-0">
            <i class="hs-admin-list"></i> Seleção de Perfis - <small>Você pode atribuir mais de um perfil ao mesmo usuário</small>
        </h2>
        <form role="form" method="POST" action="<?=$action?>">
            <div class="btn-group justified-content mt-5">
                <?php
                if(!empty($db_roles)) {
                    foreach ($db_roles as $db_role) {
                        ?>
                        <label class="u-check g-pl-0">
                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0" <?=(in_array($db_role->getId(),$arr_roles)) ? 'checked=""' : ''; ?>
                                   type="checkbox"
                                   name="roles[]"
                                   value="<?= $db_role->getId(); ?>">
                            <span class="btn btn-md btn-block u-btn-outline-lightgray g-color-white--checked g-bg-primary--checked rounded-0">
                                <?= $db_role->getName(); ?>
                            </span>
                        </label>
                        <?php
                    }
                }
                ?>
            </div>
            <hr class="g-brd-gray-light-v7 g-mx-minus-20">
            <button type="submit" name="submit" class="btn btn-success" >
                <i class="fa fa-save"></i> <?=$this->translate("Salvar");?>
            </button>
            <button type="reset" name="submit" class="btn btn-danger" >
                <i class="fa fa-eraser"></i> <?=$this->translate("Limpar");?>
            </button>
            <a class="btn btn-info"  href="<?=$return?>">
                <i class="fa fa-arrow-circle-o-left"></i> <?=$this->translate("Retornar");?>
            </a>
        </form>
    </div>
</div>

