<!-- END PRELOADING -->
<!-- BEGIN HEADER -->
<header class="header header-home">
    <div class="in-header">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="header-bottom">
                        <div class="row">
                            <div class="col-md-3 col-logo">
                                <a href="index.html">
                                    <div class="logo">
                                        <img src="/site/logo.png" alt="logo">
                                    </div>
                                </a>
                            </div>
                            <div class="col-md-9 col-nav">
                                <div class="nav-header">
                                    <nav id="main_nav" class="navbar navbar-expand-lg ">
                                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#respmenu" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                            <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
                                        </button>
                                        <div class="collapse navbar-collapse" id="respmenu">
                                            <ul class="nav navbar-nav menu">
                                                <li>
                                                    <a href="#goto-about" class="page-scroll">QUEM SOMOS</a>
                                                </li>
                                                <li>
                                                    <a href="#goto-services" class="page-scroll">COMO FUNCIONA</a>
                                                </li>
                                                <li>
                                                    <a href="#goto-pricing" class="page-scroll">ESPECIALIDADES</a>
                                                </li>
                                                <li>
                                                    <a href="#contato" class="page-scroll">CONTATO</a>
                                                </li>
                                                <li>
                                                    <a href="<?=$this->url('admin');?>" target="blank" class="page-scroll">BACKOFFICE</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><coingecko-coin-price-marquee-widget coin-ids="bitcoin,ethereum,eos,ripple,litecoin" currency="usd" background-color="#ffffff" locale="pt" vce-ready=""></coingecko-coin-price-marquee-widget>
</header>
<!-- END HEADER -->
<!-- BEGIN SLIDER -->
<section class="home-slider">
    <div id="home-slider" class="owl-carousel owl-loaded owl-drag">
        <!-- slide item -->

        <!-- end slide item -->
        <!-- slide item -->

        <!-- end slide item -->
        <!-- slide item -->

        <!-- end slide item -->
        <div class="owl-stage-outer">
            <div class="owl-stage" style="transform: translate3d(-4053px, 0px, 0px); transition: all 0.25s ease 0s; width: 9457px;">
                <div class="owl-item cloned" style="width: 1351px;">
                    <div class="item">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="slide-caption">
                                        <h2 data-animation-in="fadeInUp" data-animation-out="animate-out fadeOutDown" style="max-width: 560px; ">MUITO MAIS<br> DO QUE INVESTIMENTO</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="filter-slider"></div>
                        <div class="slide-item">
                            <img src="/site/slide2.jpg" alt="slide">
                        </div>
                    </div>
                </div>
<!--                <div class="owl-item cloned" style="width: 1351px;">-->
<!--                    <div class="item">-->
<!--                        <div class="container">-->
<!--                            <div class="row">-->
<!--                                <div class="col-md-12">-->
<!--                                    <div class="slide-caption">-->
<!--                                        <h2 data-animation-in="fadeInUp" data-animation-out="animate-out fadeOutDown" style="max-width: 560px; s">CONECTANDO VOCÊ AS MELHORES SOLUÇÕES.</h2>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="filter-slider"></div>-->
<!--                        <div class="slide-item">-->
<!--                            <img src="/site/slide3.jpg" alt="slide">-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="owl-item" style="width: 1351px;">-->
<!--                    <div class="item">-->
<!--                        <div class="container">-->
<!--                            <div class="row">-->
<!--                                <div class="col-md-12">-->
<!--                                    <div class="slide-caption">-->
<!--                                        <h2 data-animation-in="fadeInUp" data-animation-out="animate-out fadeOutDown" style="max-width: 560px; " class="">CONECTANDO VOCÊ AS MELHORES SOLUÇÕES</h2>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="filter-slider"></div>-->
<!--                        <div class="slide-item">-->
<!--                            <img src="/site/slide1.jpg" alt="slide">-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
                <div class="owl-item active" style="width: 1351px;">
                    <div class="item">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="slide-caption">
                                        <h2 data-animation-in="fadeInUp" data-animation-out="animate-out fadeOutDown" style="max-width: 560px; " class="">MUITO MAIS<br> DO QUE INVESTIMENTO</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="filter-slider"></div>
                        <div class="slide-item">
                            <img src="/site/slide2.jpg" alt="slide">
                        </div>
                    </div>
                </div>
<!--                <div class="owl-item" style="width: 1351px;">-->
<!--                    <div class="item">-->
<!--                        <div class="container">-->
<!--                            <div class="row">-->
<!--                                <div class="col-md-12">-->
<!--                                    <div class="slide-caption">-->
<!--                                        <h2 data-animation-in="fadeInUp" data-animation-out="animate-out fadeOutDown" style="max-width: 560px; s">CONECTANDO VOCÊ AS MELHORES SOLUÇÕES.</h2>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="filter-slider"></div>-->
<!--                        <div class="slide-item">-->
<!--                            <img src="/site/slide3.jpg" alt="slide">-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="owl-item cloned" style="width: 1351px;">-->
<!--                    <div class="item">-->
<!--                        <div class="container">-->
<!--                            <div class="row">-->
<!--                                <div class="col-md-12">-->
<!--                                    <div class="slide-caption">-->
<!--                                        <h2 data-animation-in="fadeInUp" data-animation-out="animate-out fadeOutDown" style="max-width: 560px; ">CONECTANDO VOCÊ AS MELHORES SOLUÇÕES</h2>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="filter-slider"></div>-->
<!--                        <div class="slide-item">-->
<!--                            <img src="/site/slide1.jpg" alt="slide">-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
                <div class="owl-item cloned" style="width: 1351px;">
                    <div class="item">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="slide-caption">
                                        <h2 data-animation-in="fadeInUp" data-animation-out="animate-out fadeOutDown" style="max-width: 560px; ">MUITO MAIS<br> DO QUE INVESTIMENTO</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="filter-slider"></div>
                        <div class="slide-item">
                            <img src="/site/slide2.jpg" alt="slide">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="owl-nav">
            <div class="owl-prev">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
            </div>
            <div class="owl-next">
                <i class="fa fa-angle-right" aria-hidden="true"></i>
            </div>
        </div>
        <div class="owl-dots disabled"></div>
    </div>
</section>
<!-- END SLIDER -->
<!-- BEGIN IMAGE MENU -->

<section class="section-info" id="goto-about">
    <div class="container">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <div class="section-title">
                    <br><br><br><br><br><br>
                    <h1>QUEM <span class="font-theme-color">SOMOS</span></h1>
                </div>
                <div class="si-about">
                    Somos um grupo privado de investidores, que atua em diversos mercados tendo como foco o mercado internacional de moedas.
                    <br>
                    Oferecemos aos nossos clientes as melhores e mais modernas soluções no mercado de criptoativos através de uma plataforma global e profissionais capacitados.<br><br>
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/1la-JyI5sE0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</section>



<section id="goto-services" class="service">
    <div class="container">
        <div class="row">
            <div class="col-md-12 no-padding">
                <div class="cm-left">
                    <div class="cm-left-content-layer">
                        <div class="cm-left-content">
                            <div class="section-title">
                                <h1 style="text-align: center; font-size:150%">LEVANDO VOCÊ AS MELHORES SOLUÇÕES.</h1>
                            </div>
                        </div>
                        <div class="cmlc-bg"></div>
                    </div>
                    <div class="bg-cm" style="background-image: url(&#39;img/bg-image2.jpg&#39;);">
                    </div>
                </div>
                <div class="cm-right">
                    <div class="cm-right-wrap">
                        <div class="section-title">
                            <h1>COMO FUNCIONA</h1>
                            <p>
                                Oferecemos aos nossos clientes as melhores e mais modernas soluções no mercado de criptoativos através de uma plataforma global e profissionais capacitados.
                            </p>
                            <div class="why-list">
                                <div class="wl-box">
                                    <i class="fa fa-user wl-box-one"></i>
                                    <br><br><h5>CONHEÇA</h5>
                                    <p>
                                        Procure um de nossos Advisors e cadastre-se em nossa plataforma
                                    </p>
                                </div>
                                <div class="wl-box">
                                    <i class="fa fa-chart-line wl-box-one"></i>
                                    <br><br><h5>INVISTA</h5>
                                    <p>
                                        Escolha um de nossos planos e deposite seus bitcoins.
                                    </p>
                                </div>
                                <div class="wl-box">
                                    <i class="fa fa-chart-bar wl-box-one"></i>
                                    <br><br><h5>GANHE</h5>
                                    <p>
                                        Armazene e rentabilize seus bitcoins de forma segura
                                    </p>
                                </div>

                                <div style="clear:both"></div><br><br>
                                <a href="https://drive.google.com/file/d/1Dp6xigb-P0K6xyHatI36UPO5hsvnW_4z/view?usp=sharing"><img src="/site/botao-baixar.png"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section id="playcounter" class="counter">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title">
                    <h1>NOSSOS NUMEROS</h1>
                </div>
            </div>
        </div>
        <div class="counter-value">
            <div class="row">
                <div class="col-md-6">
                    <div class="wrap-ci">
                        <div class="count-number">
                            <div class="ct-top">
                                <i class="fa fa-smile"></i>	<span class="count">100</span>&nbsp;%&nbsp;SATISFAÇÃO
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="wrap-ci">
                        <div class="count-number">
                            <div class="ct-top">
                                <i class="fa fa-users"></i>&nbsp;+&nbsp;<span class="count">300</span>&nbsp;AFILIADOS
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bg-img-counter">
        <div class="bg-img-layer"></div>
        <div class="bg-img-banner parallax-stellar" data-stellar-background-ratio="0.5" style="background-image: url(&quot;img/counter.jpg&quot;); background-position: 50% 1057.5px;">
        </div>
    </div>
</section>

<section class="price" id="goto-pricing">
    <div class="container">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <div class="section-title">
                    <h1>NOSSAS ESPECIALIDADES</h1>
                    <p>Nosso principal canal de investimento são em operações realizadas no maior e mais líquido mercado do mundo, o mercado de moedas.</p>
                    <h1>Por que o foco em moedas?</h1>
                </div>
            </div>
        </div>
        <div class="box-price-list">
            <div class="row">
                <div class="col-md-4">
                    <div class="pricingplanitem theme-transition ">
                        <h3 style="background-image: url(img/pricing.jpg); background-size: 100% auto;background-position: right -70;">Diversificação</h3>
                        <div class="pricingplanitemdescwrap">
                            <p>
                                <br>Seu enorme volume de negociações representa a maior classe de instrumentos financeiros do mundo.<br><br><br>
                            </p>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="pricingplanitem theme-transition ">
                        <h3 style="background-image: url(img/pricingb.jpg); background-size: 100% auto;background-position: right bottom;">Cobertura Global</h3>
                        <div class="pricingplanitemdescwrap">
                            <p>
                                <br>Com ausência de fronteiras geográficas, o mercado é controlado por instituições regimentais e reguladoras de cada país onde é efetuada a operação de câmbio.<br>
                            </p></div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="pricingplanitem theme-transition ">
                        <h3 style="background-image: url(img/pricingc.jpg); background-size: 100% auto;background-position: right bottom;">Eventos de risco</h3>
                        <div class="pricingplanitemdescwrap">
                            <p>
                                <br>Nossa equipe de profissionais identifica padrões que podem levar a potenciais movimentos no mercado, gerando assim grandes oportunidades de negócios.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br><br>
        <div class="box-price-list">
            <div class="row">
                <div class="col-md-6">
                    <div class="pricingplanitem theme-transition ">
                        <h3 style="background-image: url(img/pricingd.jpg); background-size: 100% auto;background-position: right bottom;">MERCADO AO REDOR DO RELÓGIO (24h)</h3>
                        <div class="pricingplanitemdescwrap">
                            <p>
                                <br>Mercado contínuo, 24 horas por dia, 7 dias por semana, 365 dias por ano.<br><br>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="pricingplanitem theme-transition ">
                        <h3 style="background-image: url(img/pricinge.jpg); background-size: 100% auto;background-position: right bottom;">Controle de Níveis de Investimento</h3>
                        <div class="pricingplanitemdescwrap">
                            <p>
                                <br>Através de níveis de controle, somos capazes de gerir a carteira de nossos clientes fixando limites ao risco de acordo com cada perfil, do conservador ao arrojado.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="sc-portfolio" id="contato">
    <div class="wrap-content-page">
        <div class="container">
            <div class="contact-form">
                <div class="row">
                    <div class="col-md-12 text-center contact-desc-title">
                        <br><br><br><br>
                        <h1>FALE <span class="font-theme-color">CONOSCO</span></h1>
                        <div>

                        </div>
                    </div>
                </div>
                <div class="row ">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <div class="heading-footer-col">Envie sua mensagem</div>
                        <div class="contact-field">
                            <div class="row">
                                <center><a href="mailto:CONTATO@GOODBANK.COM.BR"><img src="/site/enviar.png" width="80%" height="auto" alt="profile"></a></center>
                            </div>
                            <br><br><br><br>
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="goto-testimonial" class="testimonial">
    <div class="tst-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <div class="section-title">
                        <h1>PARCEIROS</h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="wrap-item-testimonial">
                        <div id="testimonial" class="owl-carousel owl-loaded owl-drag">
                            <!-- item -->

                            <!-- end item -->
                            <!-- item -->

                            <!-- end item -->
                            <!-- item -->

                            <!-- end item -->
                            <!-- item -->

                            <!-- end item -->
                            <!-- item -->

                            <!-- end item -->
                            <!-- item -->

                            <!-- end item -->
                            <!-- item -->

                            <!-- end item -->
                            <div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-2775px, 0px, 0px); transition: all 0.25s ease 0s; width: 8325px;"><div class="owl-item cloned" style="width: 555px;"><div class="item space">
                                            <a href="https://pt.bitcointoyou.com/"><img src="/site/04.png" alt="profile"></a>
                                        </div></div><div class="owl-item cloned" style="width: 555px;"><div class="item space">
                                            <a href="https://www.blockchain.com/"><img src="/site/05.png" alt="profile"></a>
                                        </div></div><div class="owl-item cloned" style="width: 555px;"><div class="item space">
                                            <a href="https://www.fxpro.com/"><img src="/site/06.png" alt="profile"></a>
                                        </div></div><div class="owl-item cloned" style="width: 555px;"><div class="item space">
                                            <a href="https://www.neteller.com/pt"><img src="/site/07.png" alt="profile"></a>
                                        </div></div><div class="owl-item" style="width: 555px;"><div class="item space">
                                            <a href="https://www.activtrades.com/pt/"><img src="/site/01.png" alt="profile"></a>
                                        </div></div><div class="owl-item active" style="width: 555px;"><div class="item space">
                                            <a href="https://www.bet365.com/#/HO/"><img src="/site/02.png" alt="profile"></a>
                                        </div></div><div class="owl-item active" style="width: 555px;"><div class="item space">
                                            <a href="https://www.betfair.com/br"><img src="/site/03.png" alt="profile"></a>
                                        </div></div><div class="owl-item" style="width: 555px;"><div class="item space">
                                            <a href="https://pt.bitcointoyou.com/"><img src="/site/04.png" alt="profile"></a>
                                        </div></div><div class="owl-item" style="width: 555px;"><div class="item space">
                                            <a href="https://www.blockchain.com/"><img src="/site/05.png" alt="profile"></a>
                                        </div></div><div class="owl-item" style="width: 555px;"><div class="item space">
                                            <a href="https://www.fxpro.com/"><img src="/site/06.png" alt="profile"></a>
                                        </div></div><div class="owl-item" style="width: 555px;"><div class="item space">
                                            <a href="https://www.neteller.com/pt"><img src="/site/07.png" alt="profile"></a>
                                        </div></div><div class="owl-item cloned" style="width: 555px;"><div class="item space">
                                            <a href="https://www.activtrades.com/pt/"><img src="/site/01.png" alt="profile"></a>
                                        </div></div><div class="owl-item cloned" style="width: 555px;"><div class="item space">
                                            <a href="https://www.bet365.com/#/HO/"><img src="/site/02.png" alt="profile"></a>
                                        </div></div><div class="owl-item cloned" style="width: 555px;"><div class="item space">
                                            <a href="https://www.betfair.com/br"><img src="/site/03.png" alt="profile"></a>
                                        </div></div><div class="owl-item cloned" style="width: 555px;"><div class="item space">
                                            <a href="https://pt.bitcointoyou.com/"><img src="/site/04.png" alt="profile"></a>
                                        </div></div></div></div><div class="owl-nav disabled"><div class="owl-prev"><i class="fa fa-angle-left" aria-hidden="true"></i></div><div class="owl-next"><i class="fa fa-angle-right" aria-hidden="true"></i></div></div><div class="owl-dots"><div class="owl-dot active"><span></span></div><div class="owl-dot"><span></span></div><div class="owl-dot"><span></span></div><div class="owl-dot"><span></span></div></div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bg-tst">
        <div class="bg-color-tst"></div>
        <div class="bg-img-tst parallax-stellar testimonial-parallax" style="background-image: url(&quot;img/testm.jpg&quot;); background-position: 50% 2021.77px;" data-stellar-background-ratio="0.5">
        </div>
    </div>
</section>
