<?php
$coluna = $this->chave;
$controller = $this->controller;
$em = $this->em;
$functions = new \Base\Controller\BaseFunctions();

$vl = null;
if(isset($_POST[$controller . '_' . $chave])) {
    $vl = $_POST[$controller . '_' . $chave];
}

if(isset($_SESSION['filter-form'][$controller . '_' . $chave])) {
    $vl     = $_SESSION['filter-form'][$controller . '_' . $chave];
}


switch ($coluna){
    case "document":
        ?>

        <div class="form-group g-mb-30">
            <label class="g-mb-10" for="<?= $controller?>_<?=$chave?>"><?= $filter['label'] ?></label>

            <div class="g-pos-rel">
                      <span class="g-pos-abs g-top-0 g-right-0 d-block g-width-40 h-100 opacity-0 g-opacity-1--success">
	                  	<i class="hs-admin-check g-absolute-centered g-font-size-default g-color-secondary"></i>
	                	</span>
                <input id="<?= $controller?>_<?=$chave?>"
                       name="<?= $controller ?>_<?=$chave?>"
                       class="form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-20 g-px-14 g-py-10"
                       type="text"
                       placeholder=""
                       value="<?= $vl ?>">
            </div>
        </div>
        <?php
        break;
    case "active":
        ?>
        <div class="g-mb-30">
            <label class="g-mb-10"><?= $filter['label'] ?></label>

            <div class="form-group u-select--v3 g-pos-rel g-brd-gray-light-v7 g-rounded-25 mb-0">
                <select name="<?= $controller ?>_<?=$chave?>"
                        id="<?= $controller?>_<?=$chave?>"
                        class="js-select u-select--v3-select u-sibling w-100"
                        title="<?= $filter['label'] ?>" style="display: none;">
                    <option <?=($vl === null)?'selected':''?> value="">Selecione...</option>
                    <?php
                    $class = '
                    <span class="d-flex align-items-center w-100">
                        <i class="hs-admin-close g-font-size-18 g-mr-15"></i><span>Não</span>
                    </span>';
                    ?>
                    <option <?=($vl === '0')?'selected':'';?>
                            value="0"
                            data-content='<?=$class?>'>
                        Não
                    </option>
                    <?php
                    $class = '
                    <span class="d-flex align-items-center w-100">
                        <i class="hs-admin-check g-font-size-18 g-mr-15"></i><span>Sim</span>
                    </span>';
                    ?>
                    <option <?=($vl === '1')?'selected':'';?>
                            value="1"
                            data-content='<?=$class?>'>
                        Sim
                    </option>
                </select>

                <div class="d-flex align-items-center g-absolute-centered--y g-right-0 g-color-gray-light-v6 g-color-lightblue-v9--sibling-opened g-mr-15">
                    <i class="hs-admin-angle-down"></i>
                </div>
            </div>
        </div>
        <?php
        break;
    case "plan":
        /**
         * @var \PaymentMethod\Entity\PaymentMethod[] $db_payment_methods
         */
        $db_entities = $em->getRepository('Plan\Entity\Plan')->findAll();
        ?>
        <div class="g-mb-30">
            <label class="g-mb-10"><?= $filter['label'] ?></label>

            <div class="form-group u-select--v3 g-pos-rel g-brd-gray-light-v7 g-rounded-25 mb-0">
                <select name="<?= $controller ?>_<?=$chave?>"
                        id="<?= $controller?>_<?=$chave?>"
                        class="js-select u-select--v3-select u-sibling w-100"
                        title="<?= $filter['label'] ?>" style="display: none;">
                    <option <?=($vl === null)?'selected':''?> value="">Selecione...</option>
                    <?php
                    if(!empty($db_entities)){
                        foreach ($db_entities as $db_entity) {
                            if(is_numeric($vl)){
                                $vl = $vl*1;
                            }
                            ?>
                            <option <?=($vl === $db_entity->getId())?'selected':''?> value="<?=$db_entity->getId()?>">
                                <?=$db_entity?>
                            </option>
                            <?php
                        }
                    }
                    ?>
                </select>

                <div class="d-flex align-items-center g-absolute-centered--y g-right-0 g-color-gray-light-v6 g-color-lightblue-v9--sibling-opened g-mr-15">
                    <i class="hs-admin-angle-down"></i>
                </div>
            </div>
        </div>
        <?php
        break;
    case "payment-method":
        /**
         * @var \PaymentMethod\Entity\PaymentMethod[] $db_payment_methods
         */
        $db_payment_methods = $em->getRepository('PaymentMethod\Entity\PaymentMethod')->findAll();
        ?>
        <div class="g-mb-30">
            <label class="g-mb-10"><?= $filter['label'] ?></label>

            <div class="form-group u-select--v3 g-pos-rel g-brd-gray-light-v7 g-rounded-25 mb-0">
                <select name="<?= $controller ?>_<?=$chave?>"
                        id="<?= $controller?>_<?=$chave?>"
                        class="js-select u-select--v3-select u-sibling w-100"
                        title="<?= $filter['label'] ?>" style="display: none;">
                    <option <?=($vl === null)?'selected':''?> value="">Selecione...</option>
                    <?php
                    if(!empty($db_payment_methods)){
                        foreach ($db_payment_methods as $db_payment_method) {
                            if(is_numeric($vl)){
                                $vl = $vl*1;
                            }
                            ?>
                            <option <?=($vl === $db_payment_method->getId())?'selected':''?> value="<?=$db_payment_method->getId()?>">
                                <?=$db_payment_method->getName()?>
                            </option>
                            <?php
                        }
                    }
                    ?>
                </select>

                <div class="d-flex align-items-center g-absolute-centered--y g-right-0 g-color-gray-light-v6 g-color-lightblue-v9--sibling-opened g-mr-15">
                    <i class="hs-admin-angle-down"></i>
                </div>
            </div>
        </div>
        <?php
        break;
    case "category_transaction":
        /**
         * @var \CategoryTransaction\Entity\CategoryTransaction[] $db_category_transactions
         */
        $db_entities = $em->getRepository('CategoryTransaction\Entity\CategoryTransaction')->findAll();
        ?>
        <div class="g-mb-30">
            <label class="g-mb-10"><?= $filter['label'] ?></label>

            <div class="form-group u-select--v3 g-pos-rel g-brd-gray-light-v7 g-rounded-25 mb-0">
                <select name="<?= $controller ?>_<?=$chave?>"
                        id="<?= $controller?>_<?=$chave?>"
                        class="js-select u-select--v3-select u-sibling w-100"
                        title="<?= $filter['label'] ?>" style="display: none;">
                    <option <?=($vl === null)?'selected':''?> value="">Selecione...</option>
                    <?php
                    if(!empty($db_entities)){
                        foreach ($db_entities as $db_entity) {
                            if(is_numeric($vl)){
                                $vl = $vl*1;
                            }
                            ?>
                            <option <?=($vl === $db_entity->getId())?'selected':''?> value="<?=$db_entity->getId()?>">
                                <?=$db_entity->getName()?>
                            </option>
                            <?php
                        }
                    }
                    ?>
                </select>

                <div class="d-flex align-items-center g-absolute-centered--y g-right-0 g-color-gray-light-v6 g-color-lightblue-v9--sibling-opened g-mr-15">
                    <i class="hs-admin-angle-down"></i>
                </div>
            </div>
        </div>
        <?php
        break;
    default:
        ?>
        <div class="col-md-12 form-group">
            <label><?= $filter['label'] ?></label>
            <p><small>Filtro Customizado não definido</small></p>
        </div>
        <?php
}

?>
