<div class="modal fade" id="modal_rr"
     aria-labelledby="modal_cash_out_title"
     tabindex="-1"
     role="dialog"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">
                    Solicitar Renovação
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div ng-show="renew || cash_out">
                            <p class="alert alert-danger">
                                O valor total do rendimento será sacado automaticamente
                            </p>
                            <h4 class="text-center">
                                Valor de rendimento
                                R$ {{ user_plan.balance | currency:'':2:'pt-BR' }}
                            </h4>
                            <h4 class="text-center">
                                Valor do aporte
                                R$ {{ user_plan._embedded.plan.price | currency:'':2:'pt-BR' }}
                            </h4>
                            <h3 class="text-center g-bg-green g-color-white">
                                Total do saque
                                <strong>R$ {{ user_plan.balance + user_plan._embedded.plan.price | currency:'':2:'pt-BR' }}</strong>
                            </h3>
                        </div>
                        <hr class="m-2" />
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4 class="g-color-red">Ações Críticas</h4>
                                    <span class="d-flex align-self-center g-color-gray-dark-v6 g-font-weight-400">
                                        O resgate ou a renovação de contrato será habilitado somente na expiração do contrato
                                    </span>
                                </div>
                                <div class="col-md-6">
                                    <label ng-if="!cash_out" class="d-flex align-items-center justify-content-between mt-2 border border-danger p-1">
                                        <span><strong>Renovar o Contrato</strong></span>
                                        <div ng-if="getExpirationDays(user_plan.approved_date) == 0" class="u-check">
                                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-right-0"
                                                   name="renew"
                                                   ng-model="renew"
                                                   ng-click="renewChange()"
                                                   type="checkbox" value="true">
                                            <div class="u-check-icon-radio-v8">
                                                <i class="fa" data-check-icon=""></i>
                                            </div>
                                        </div>
                                        <div ng-if="getExpirationDays(user_plan.approved_date) > 0" class="u-check">
                                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-right-0"
                                                   name="renew"
                                                   disabled
                                                   type="checkbox">
                                            <div class="u-check-icon-radio-v8">
                                                <i class="fa" data-check-icon=""></i>
                                            </div>
                                        </div>
                                    </label>
                                </div>
                                <div class="col-md-6">
                                    <label ng-if="!renew" class="d-flex align-items-center justify-content-between mt-2 border border-danger p-1">
                                        <span><strong>Solicitar o Resgate</strong></span>
                                        <div ng-if="getExpirationDays(user_plan.approved_date) == 0" class="u-check">
                                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-right-0"
                                                   name="cash_out"
                                                   ng-model="cash_out"
                                                   ng-click="cachOutChange()"
                                                   type="checkbox" value="true">
                                            <div class="u-check-icon-radio-v8">
                                                <i class="fa" data-check-icon=""></i>
                                            </div>
                                        </div>
                                        <div ng-if="getExpirationDays(user_plan.approved_date) > 0" class="u-check">
                                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-right-0"
                                                   name="cash_out"
                                                   disabled
                                                   type="checkbox">
                                            <div class="u-check-icon-radio-v8">
                                                <i class="fa" data-check-icon=""></i>
                                            </div>
                                        </div>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <span ng-if="enableCashOut()" class="text-danger">
                    Saque disponível somente nos dias:
                    <center>
                        <ul style="list-style: none;padding: 0;margin: 20px 0px 0px 0px;">
                            <li style="display: inline" class="alert alert-danger" ng-repeat="day in canDays">
                                {{ day }}
                            </li>
                        </ul>
                    </center>
                </span>
                <div class="row">
                    <div class="col-md-12 form-group">
                        <label>
                            <strong>Você deseja receber o saque por onde?</strong>
                        </label>
                        <div class="btn-group justified-content">
                            <label class="u-check">
                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                       ng-model="receive_method"
                                       checked=""
                                       type="radio" ng-value="0" value="0">
                                <span class="btn btn-md btn-block u-btn-outline-lightgray g-color-white--checked g-bg-primary--checked rounded-0">
                                    <i class="fa fa-bank"></i>&nbsp;Conta Bancária
                                </span>
                            </label>
                            <label class="u-check">
                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                       ng-model="receive_method"
                                       type="radio" ng-value="1" value="1">
                                <span class="btn btn-md btn-block u-btn-outline-lightgray g-color-white--checked g-bg-primary--checked g-brd-left-none--md rounded-0">
                                    <i class="fa fa-bitcoin"></i>&nbsp;Carteira Bitcoin
                                </span>
                            </label>
                        </div>
                    </div>
                    <div ng-show="receive_method == 0" class="col-md-12 form-group ">
                        <label>
                            <strong>Selecione sua conta bancária</strong>
                        </label>
                        <p ng-show="accounts.length == 0" class="alert alert-danger">
                            Você não possui carteira cadastrada:
                            <a class="btn btn-info" href="<?=$this->url('user-view',array('id' => $this->userIdentity('User')->getId()))?>?tab=account">
                                Cadastrar Conta Bancária
                            </a>
                        </p>
                        <select ng-show="accounts.length > 0" class="form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-20 g-px-14 g-py-10"
                                name="wallet"
                                ng-model="user_plan.account"
                                required>
                            <option value="">Selecione...</option>
                            <option ng-repeat="account in accounts"
                                    ng-value="account.id"
                                    value="{{ account.id }}">
                                {{ account.account_number }}
                            </option>
                        </select>
                    </div>
                    <div ng-if="receive_method == 1" class="col-md-12 form-group ">
                        <label>
                            <strong>Selecione sua carteira bitcoin</strong>
                        </label>
                        <p ng-show="wallets.length == 0" class="alert alert-danger">
                            Você não possui carteira cadastrada:
                            <a class="btn btn-info" href="<?=$this->url('user-view',array('id' => $this->userIdentity('User')->getId()))?>?tab=wallet">
                                Cadastrar Carteira
                            </a>
                        </p>
                        <select ng-show="wallets.length > 0" class="form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-20 g-px-14 g-py-10"
                                name="wallet"
                                ng-model="user_plan.wallet"
                                required>
                            <option value="">Selecione...</option>
                            <option ng-repeat="wallet in wallets"
                                    ng-value="wallet.id"
                                    value="{{ wallet.id }}">
                                {{ wallet.account }}
                            </option>
                        </select>
                    </div>
                    <div ng-if="renew && 1==2" class="col-md-12 form-group ">
                        <label>
                            <strong>Selecione o comprovante</strong>
                        </label>
                        <input class="form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-20 g-px-14 g-py-10"
                                name="receipt"
                                ng-model="user_plan.receipt"
                                value=""
                                type="file"
                                required />

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    Fechar
                </button>
                <button type="button"
                        class="btn btn-primary"
                        ng-show="enableSolicitation"
                        ng-disabled="enableCashOut()"
                        ng-click="sendRR()">
                    Solicitar
                </button>
                <button type="button"
                        class="btn btn-primary"
                        disabled
                        ng-show="!enableSolicitation">
                    <i class="fa fa-refresh"></i> Aguarde
                </button>
            </div>
        </div>
    </div>
</div>
