<?php
$functions = new \Base\Controller\BaseFunctions();
$controller = $this->listView['controller'];
$filters = $this->listView['filters'];

$arr_element = array();

if(!empty($this->form))
{
    foreach($this->form as $k => $element)
    {

        $arr_element[$controller.'_'.$k] = $element;
    }
}

if(!empty($filters)) {
    ?>
    <div class="g-brd-around g-brd-gray-light-v7 g-rounded-4 g-pa-15 g-pa-20--md g-mb-30">
        <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-black g-mb-20">
            <i class="fa fa-filter"></i>&nbsp;Filtro
        </h3>

        <form method="post" action="">
            <input type="hidden" name="controller" value="<?=$controller?>"/>
            <?php

            foreach ($filters as $k => $filter) {
                echo $this->partial('filter/'.$filter['type'],array(
                    'em'            => $this->em,
                    'chave'         => $k,
                    'filter'        => $filter,
                    'controller'    => $controller,
                    'entity'        => $this->entity,
                    'element'       => $arr_element[$controller. '_' .$k]
                ));
            }
            ?>


            <button type="submit" class="btn btn-xl g-brd-around g-rounded-50 u-btn-gradient-v1 g-width-160--md g-font-size-default"
                    name="filter-form">
                <i class="hs-admin-filter"></i>&nbsp;Filtrar
            </button>
            <?php
            if(isset($_SESSION['filter-form'])) {
                $clear_filter_url = $this->url($this->listView['route'], array(
                    'controller' => $this->controller,
                    'action' => 'clear-filter'
                ));
                ?>
                <a class="btn btn-xl g-brd-around g-rounded-50 u-btn-red g-width-160--md g-font-size-default"
                   href="<?= $clear_filter_url ?>">
                    <i class="fa fa-close"></i>&nbsp;Limpar Filtro
                </a>
                <?php
            }
        ?>
        </form>
    </div>
    <?php
}
?>
