<!-- JS Global Compulsory -->
<script src="/admin/assets/vendor/jquery-migrate/jquery-migrate.min.js"></script>

<script src="/assets/vendor/popper.js/popper.min.js"></script>
<script src="/assets/vendor/bootstrap/bootstrap.min.js"></script>

<script src="/assets/vendor/cookiejs/jquery.cookie.js"></script>

<!-- jQuery UI Core -->
<script src="/assets/vendor/jquery-ui/ui/widget.js"></script>
<script src="/assets/vendor/jquery-ui/ui/version.js"></script>
<script src="/assets/vendor/jquery-ui/ui/keycode.js"></script>
<script src="/assets/vendor/jquery-ui/ui/position.js"></script>
<script src="/assets/vendor/jquery-ui/ui/unique-id.js"></script>
<script src="/assets/vendor/jquery-ui/ui/safe-active-element.js"></script>

<!-- jQuery UI Helpers -->
<script src="/assets/vendor/jquery-ui/ui/widgets/menu.js"></script>
<script src="/assets/vendor/jquery-ui/ui/widgets/mouse.js"></script>

<!-- jQuery UI Widgets -->
<script src="/assets/vendor/jquery-ui/ui/widgets/datepicker.js"></script>

<!-- JS Plugins Init. -->
<script src="/assets/vendor/appear.js"></script>
<script src="/admin/assets/vendor/bootstrap-select/js/bootstrap-select.min.js"></script>
<script src="/admin/assets/vendor/flatpickr/dist/js/flatpickr.min.js"></script>
<script src="/assets/vendor/malihu-scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="/admin/assets/vendor/chartist-js/chartist.min.js"></script>
<script src="/admin/assets/vendor/chartist-js-tooltip/chartist-plugin-tooltip.js"></script>
<script src="/admin/assets/vendor/fancybox/jquery.fancybox.min.js"></script>
<script src="/admin/assets/vendor/ion-range-slider/js/ion.rangeSlider.min.js"></script>

<!-- JS Unify -->
<script src="/assets/js/hs.core.js"></script>
<script src="/admin/assets/js/components/hs.side-nav.js"></script>
<script src="/assets/js/helpers/hs.hamburgers.js"></script>
<script src="/admin/assets/js/components/hs.range-datepicker.js"></script>
<script src="/assets/js/components/hs.datepicker.js"></script>
<script src="/assets/js/components/hs.dropdown.js"></script>
<script src="/assets/js/components/hs.scrollbar.js"></script>
<script src="/admin/assets/js/components/hs.area-chart.js"></script>
<script src="/admin/assets/js/components/hs.donut-chart.js"></script>
<script src="/admin/assets/js/components/hs.bar-chart.js"></script>
<script src="/admin/assets/js/components/hs.range-slider.js"></script>
<script src="/assets/js/helpers/hs.focus-state.js"></script>
<script src="/admin/assets/js/components/hs.popup.js"></script>
<script src="/admin/assets/vendor/noty/lib/noty.min.js"></script>
<script src="/admin/assets/cropper/cropper.min.js"></script>
<script src="/admin/assets/js/summernote.js"></script>
<script src="/assets/js/bootbox.js"></script>
<!-- JS Custom -->
<script src="/assets/js/custom.js"></script>
<script src="/assets/js/crypto-md5.js"></script>
<script src="/assets/js/angular-locale_pt-br.js"></script>
