<!-- Favicon -->
<link rel="shortcut icon" href="/assets/favicon.ico">
<!-- Google Fonts -->
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans%3A400%2C300%2C500%2C600%2C700%7CPlayfair+Display%7CRoboto%7CRaleway%7CSpectral%7CRubik">
<link rel="stylesheet" href="/assets/css/pe-icon-7-stroke.css">

<!-- CSS Global Compulsory -->
<link rel="stylesheet" href="/assets/vendor/bootstrap/bootstrap.min.css">
<!-- CSS Global Icons -->
<link rel="stylesheet" href="/assets/vendor/icon-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="/assets/vendor/icon-line/css/simple-line-icons.css">
<link rel="stylesheet" href="/assets/vendor/icon-etlinefont/style.css">
<link rel="stylesheet" href="/assets/vendor/icon-line-pro/style.css">
<link rel="stylesheet" href="/assets/vendor/icon-hs/style.css">

<link rel="stylesheet" href="/admin/assets/vendor/hs-admin-icons/hs-admin-icons.css">

<link rel="stylesheet" href="/assets/vendor/animate.css">
<link rel="stylesheet" href="/assets/vendor/malihu-scrollbar/jquery.mCustomScrollbar.min.css">

<link rel="stylesheet" href="/admin/assets/vendor/flatpickr/dist/css/flatpickr.min.css">
<link rel="stylesheet" href="/admin/assets/vendor/bootstrap-select/css/bootstrap-select.min.css">
<link rel="stylesheet" href="/admin/assets/vendor/ion-range-slider/css/ion.rangeSlider.css">
<link rel="stylesheet" href="/admin/assets/vendor/chartist-js/chartist.min.css">
<link rel="stylesheet" href="/admin/assets/vendor/chartist-js-tooltip/chartist-plugin-tooltip.css">
<link rel="stylesheet" href="/assets/vendor/fancybox/jquery.fancybox.min.css">

<link rel="stylesheet" href="/assets/vendor/hamburgers/hamburgers.min.css">

<link rel="stylesheet" href="/admin/assets/vendor/noty/lib/noty.css">

<link rel="stylesheet" type="text/css" media="screen" href="/admin/assets/cropper/cropper.css">

<!-- CSS Unify -->
<link rel="stylesheet" href="/admin/assets/css/unify-admin.css">
<link rel="stylesheet" href="/admin/assets/css/summernote.css">
<!-- CSS Customization -->
<link rel="stylesheet" href="/assets/css/custom.css">
<link rel="stylesheet" href="/admin/assets/css/custom.css">
