<?php
$url_sponsor = $_SERVER['REQUEST_SCHEME'].'://'.$_SERVER['SERVER_NAME'];
$url_sponsor .= $this->url('user-register');
$url_sponsor .= '?sponsor=' . $this->userIdentity('User')->getId();
/**
 * @var \Register\Entity\User $db_user
 */
$db_user = $this->userIdentity('User');
$incomplete = false;
$needles = array(
    'Celphone',
    'Phone',
    'Document',
    'Birthdate',
    'Gender'
);

if(!empty($needles)){
    foreach ($needles as $needle){
        $method = 'get' . $needle;
        if($db_user->$method() === null || $db_user->$method() === ''){
            $incomplete = true;
        }
    }
}

?>
<div class="g-hidden-sm-down bg-green-light g-pa-20">
    <ul class="u-list-inline g-color-gray-dark-v6">
        <li class="list-inline-item g-mr-10">
            <a class="u-link-v5 g-color-white g-valign-middle" href="/admin-home">
                <i class="fa fa-dashboard"></i>&nbsp;&nbsp;Dashboard
            </a>
        </li>
    </ul>
</div>
<div class="g-pa-20">
    <div class="row">
        <div class="col-md-12">
            <?php
            if($incomplete){
                ?>
                <div style="margin-left: 0;margin-right: 0;" class="row alert alert-danger">
                    <div class="col-md-9 pt-2">
                        <i class="hs-admin-face-sad"></i>&nbsp;&nbsp;
                        Você precisa completar suas informações de perfil,
                        por favor acesse a área de informações gerais da conta.
                    </div>
                    <div class="col-md-3">
                        <center>
                            <a class="btn btn-info"
                               href="<?=$this->url('user-view',array('id' => $this->userIdentity('User')->getId()));?>">
                                Completar meu cadastro
                            </a>
                        </center>
                    </div>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?php
            if($db_user->hasThisRole('Administrador')){
                ?>
                <div class="card g-brd-gray-light-v7 g-rounded-3 mb-4">
                    <header class="card-header g-bg-black g-brd-bottom-none g-px-15 g-px-30--sm g-pt-15 g-pt-20--sm g-pb-10 g-pb-15--sm">
                        <div class="media">
                            <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-white g-mr-10 mb-0">
                                <i class="hs-admin-rocket"></i>&nbsp;Resumo do Sistema
                            </h3>
                        </div>
                    </header>
                    <div class="card-block g-font-weight-300 g-pa-20">
                        <div class="row">
                            <div class="col-md-6 d-flex align-items-center">
                                <div class="media">
                                    <div class="d-flex g-mr-15">
                                        <div class="u-header-dropdown-icon-v1 g-pos-rel g-width-60 g-height-60 g-bg-green g-font-size-18 g-font-size-24--md g-color-white rounded-circle">
                                            <i class="hs-admin-money g-absolute-centered"></i>
                                        </div>
                                    </div>

                                    <div class="media-body align-self-center">
                                        <div class="d-flex align-items-center g-mb-5">
                                        <span class="g-font-size-24 g-line-height-1 g-color-green">
                                            <strong>
                                                <?="R$" . number_format($this->total_rendimento_all, 2, ',', '.')?>
                                            </strong>
                                        </span>
                                        </div>
                                        <h6 class="g-font-size-16 g-font-weight-300 g-color-gray-dark-v6 mb-0">
                                            Rendimento Total
                                        </h6>
                                    </div>

                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-12">
                                        <table class="table table-striped">
                                            <tr>
                                                <td>
                                                    Ciclo Atual:
                                                </td>
                                                <td class="text-center">
                                                    <strong><?=$this->db_cycle_active;?></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Aportes Ativos:
                                                </td>
                                                <td class="text-center">
                                                    <strong><?=count($this->db_user_plans_all);?></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Total Investido:
                                                </td>
                                                <td class="text-center">
                                                    <strong><?="R$" . number_format($this->total_investido_all, 2, ',', '.')?></strong>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
            }
            ?>

            <div class="card g-brd-gray-light-v7 g-rounded-3 mb-4">
                <header class="card-header g-bg-black g-brd-bottom-none g-px-15 g-px-30--sm g-pt-15 g-pt-20--sm g-pb-10 g-pb-15--sm">
                    <div class="media">
                        <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-white g-mr-10 mb-0">
                            <i class="hs-admin-rocket"></i>&nbsp;Resumo da Conta
                        </h3>
                    </div>
                </header>
                <div class="card-block g-font-weight-300 g-pa-20">
                    <div class="row">
                        <div class="col-md-6 d-flex align-items-center">
                            <div class="media">
                                <div class="d-flex g-mr-15">
                                    <div class="u-header-dropdown-icon-v1 g-pos-rel g-width-60 g-height-60 g-bg-green g-font-size-18 g-font-size-24--md g-color-white rounded-circle">
                                        <i class="hs-admin-money g-absolute-centered"></i>
                                    </div>
                                </div>

                                <div class="media-body align-self-center">
                                    <div class="d-flex align-items-center g-mb-5">
                                        <span class="g-font-size-24 g-line-height-1 g-color-green">
                                            <strong>
                                                <?="R$" . number_format($this->total_rendimento, 2, ',', '.')?>
                                            </strong>
                                        </span>
                                    </div>
                                    <h6 class="g-font-size-16 g-font-weight-300 g-color-gray-dark-v6 mb-0">
                                        Rendimento Total
                                    </h6>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-striped">
                                        <tr>
                                            <td>
                                                Ciclo Atual:
                                            </td>
                                            <td class="text-center">
                                                <strong><?=$this->db_cycle_active;?></strong>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Aportes Ativos:
                                            </td>
                                            <td class="text-center">
                                                <strong><?=count($this->db_user_plans);?></strong>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Total Investido:
                                            </td>
                                            <td class="text-center">
                                                <strong><?="R$" . number_format($this->total_investido, 2, ',', '.')?></strong>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Indicações:
                                            </td>
                                            <td class="text-center">
                                                <strong><?=count($this->db_indicados)?></strong>
                                            </td>
                                        </tr>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card g-brd-gray-light-v7 g-pa-15 g-pa-25-30--md g-mb-30">
                <header class="media g-mb-30">
                    <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-black mb-0">
                        <i class="hs-admin-bar-chart"></i>&nbsp;Desempenho dos Investimentos
                    </h3>
                </header>

                <section>
                    <ul class="list-unstyled d-flex g-mb-45">
                        <li class="media">
                            <div class="d-flex align-self-center g-mr-8">
                                <span class="u-badge-v2--md g-pos-stc g-transform-origin--top-left g-bg-primary"></span>
                            </div>

                            <div class="media-body align-self-center g-font-size-12 g-font-size-default--md">
                                Percentual de Crescimento Mensal
                            </div>
                        </li>
                    </ul>


                    <canvas id="canvas"></canvas>
                </section>
            </div>
        </div>
        <div class="col-md-6 ">
            <?php
            if($db_user->hasThisRole('Administrador')){
                ?>
                <div class="card g-brd-gray-light-v7 g-rounded-3 mb-4">
                    <header class="card-header g-bg-black g-brd-bottom-none g-px-15 g-px-30--sm g-pt-15 g-pt-20--sm g-pb-10 g-pb-15--sm">
                        <div class="media">
                            <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-white g-mr-10 mb-0">
                                <i class="hs-admin-money"></i>&nbsp;Pendências do Administrador
                            </h3>
                        </div>
                    </header>
                    <div class="card-block g-font-weight-300 g-pa-20">
                        <div class="row">
                            <div class="col-md-6 mb-2">
                                <div class="media row">
                                    <div class="col-md-4 d-flex justify-content-center">
                                        <div class=" align-self-center g-mr-15 pb-2">
                                            <div class="u-header-dropdown-icon-v1 g-pos-rel g-width-60 g-height-60 g-bg-green g-font-size-18 g-font-size-24--md g-color-white rounded-circle">
                                                <i class="fa fa-money g-absolute-centered"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8 d-flex justify-content-center">
                                        <div class="align-self-center g-mb-5 pb-2">
                                        <span class="g-font-size-24 g-line-height-1 g-color-green text-center">
                                            <strong>
                                                <?=count($this->db_user_plans_all_deactives);?>
                                            </strong>
                                            <h6 class="g-font-size-16 g-font-weight-300 g-color-gray-dark-v6 mb-0">
                                                Aportes Inativos
                                            </h6>
                                            <?php
                                            $url = $this->url('user-plan/default',array('controller' => 'user-plan','action' => 'index'));
                                            ?>
                                            <a class="btn btn-primary mt-2 mb-0" href="<?=$url?>">
                                                Acessar
                                            </a>
                                        </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-2">
                                <div class="media row">
                                    <div class="col-md-4 d-flex justify-content-center">
                                        <div class=" align-self-center g-mr-15 pb-2">
                                            <div class="u-header-dropdown-icon-v1 g-pos-rel g-width-60 g-height-60 g-bg-green g-font-size-18 g-font-size-24--md g-color-white rounded-circle">
                                                <i class="fa fa-dollar g-absolute-centered"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8 d-flex justify-content-center">
                                        <div class="align-self-center g-mb-5 pb-2">
                                        <span class="g-font-size-24 g-line-height-1 g-color-green text-center">
                                            <strong>
                                               <?=count($this->db_solicitations_all_deactives);?>
                                            </strong>
                                            <h6 class="g-font-size-16 g-font-weight-300 g-color-gray-dark-v6 mb-0">
                                                Solicitações não atendidas
                                            </h6>
                                            <?php
                                            $url = $this->url('solicitation/default',array('controller' => 'solicitation','action' => 'index'));
                                            ?>
                                            <a class="btn btn-primary mt-2 mb-0" href="<?=$url?>">
                                                Acessar
                                            </a>
                                        </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
            }
            ?>
            <div class="card g-brd-gray-light-v7 g-rounded-3 mb-4">
                <header class="card-header g-bg-black g-brd-bottom-none g-px-15 g-px-30--sm g-pt-15 g-pt-20--sm g-pb-10 g-pb-15--sm">
                    <div class="media">
                        <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-white g-mr-10 mb-0">
                            <i class="hs-admin-money"></i>&nbsp;Cotações
                        </h3>
                    </div>
                </header>
                <div class="card-block g-font-weight-300 g-pa-20">
                    <div class="row">
                        <div class="col-md-6 mb-2">
                            <div class="media row">
                                <div class="col-md-4 d-flex justify-content-center">
                                    <div class=" align-self-center g-mr-15 pb-2">
                                        <div class="u-header-dropdown-icon-v1 g-pos-rel g-width-60 g-height-60 g-bg-green g-font-size-18 g-font-size-24--md g-color-white rounded-circle">
                                            <i class="fa fa-bitcoin g-absolute-centered"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-8 d-flex justify-content-center">
                                    <div class="align-self-center g-mb-5 pb-2">
                                        <span class="g-font-size-24 g-line-height-1 g-color-green text-center">
                                            <strong>
                                               R$ <?=number_format($this->getConfiguration('BITCOIN'), 2, ',', '.')?>
                                            </strong>
                                            <h6 class="g-font-size-16 g-font-weight-300 g-color-gray-dark-v6 mb-0">
                                                Bitcoin
                                            </h6>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 mb-2">
                            <div class="media row">
                                <div class="col-md-4 d-flex justify-content-center">
                                    <div class=" align-self-center g-mr-15 pb-2">
                                        <div class="u-header-dropdown-icon-v1 g-pos-rel g-width-60 g-height-60 g-bg-green g-font-size-18 g-font-size-24--md g-color-white rounded-circle">
                                            <i class="fa fa-dollar g-absolute-centered"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-8 d-flex justify-content-center">
                                    <div class="align-self-center g-mb-5 pb-2">
                                        <span class="g-font-size-24 g-line-height-1 g-color-green text-center">
                                            <strong>
                                               R$ <?=number_format($this->getConfiguration('DOLLAR'), 2, ',', '.')?>
                                            </strong>
                                            <h6 class="g-font-size-16 g-font-weight-300 g-color-gray-dark-v6 mb-0">
                                                Dólar
                                            </h6>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card g-brd-gray-light-v7 g-rounded-3 g-mb-30">
                <header class="card-header g-bg-black g-brd-bottom-none g-px-15 g-px-30--sm g-pt-15 g-pt-20--sm g-pb-10 g-pb-15--sm">
                    <div class="media">
                        <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-white g-mr-10 mb-0">
                            <i class="hs-admin-link"></i>&nbsp;Link de Indicação
                        </h3>
                    </div>
                </header>

                <div class="card-block">
                    <div class="row">
                        <div class="col-md-12 pb-3">
                            <h4 class="g-font-weight-300 g-font-size-18 g-font-size-22--md g-color-black g-mb-10 text-center">
                                Copie o link de indicação e envie para seus amigos <i class="hs-admin-heart"></i>
                            </h4>
                        </div>
                        <div class="col-md-12 form-group">
                            <div class="g-pos-rel">
                                <button onclick="copyToClipboard();"
                                        class="btn u-input-btn--v1 g-width-100 g-bg-primary g-rounded-right-20 g-color-white"
                                        type="button">
                                    <i class="fa fa-copy  g-font-size-16"></i>&nbsp;Copiar
                                </button>
                                <input id="copyInput"
                                       class="form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3 g-rounded-20 g-px-14 g-py-10"
                                       type="text"
                                       readonly="true"
                                       placeholder=""
                                       value="<?=$url_sponsor?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
