<?php

namespace Register\Controller;

use Acl\Entity\Role;
use Register\Entity\User;
use Register\Entity\UserRole;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;
use Base\Controller\CrudController;
use Zend\Paginator\Adapter\ArrayAdapter;
use Zend\Paginator\Paginator;
use Zend\Stdlib\Hydrator;

class UserController extends CrudController
{
    protected $route;

    public function __construct() 
    {
        $this->table = 'user';
        $this->entity = 'Register\Entity\User' ;
        $this->service = 'Register\Service\\'.$this->table ;
        $this->form = 'Register\Form\\'.$this->table ;
        $this->controller = "user";
        $this->route = "user/default";

        $this->title = "Usuários";

        $this->_listView = array(
            'title' => $this->title,
            'icon' => 'fa-fw fa fa-user',
            'route' => $this->route,
            'controller' => $this->controller,
            'actions' => array(
                'enable' =>true,
                'customs' => array(
                    'permissions' => array(
                        'rota' => 'user-role',
                        'title' => 'Perfil',
                        'enable' => true,
                        'class' => 'btn btn-warning',
                        'icon' => 'hs-admin-align-justify',
                        'group' => false,
                        'authorize' => false
                    ),
                ),
                'defaults' => array(
                    'edit' => array(
                        'enable' => true,
                        'class' => 'btn btn-info',
                        'icon' => 'fa fa-edit',
                        'title' => 'Editar',
                        'authorize' => false
                    ),
                    'delete' => array(
                        'enable' => true,
                        'class' => 'btn btn-danger decision',
                        'icon' => 'fa fa-trash',
                        'title' => 'Excluir',
                        'authorize' => false
                    ),
                    'view' => array(
                        'enable' => true,
                        'class' => 'btn btn-info',
                        'icon' => 'fa fa-eye',
                        'title' => 'Visualizar',
                        'authorize' => false
                    ),
                ),
            ),
            'fields' => array(
                'id'=>array(
                    'label' => 'Id',
                    'list' => true,
                ),
                'name'=>array(
                    'label' => 'Nome',
                    'list' => true,
                ),
                'email'=>array(
                    'label' => 'E-mail',
                    'list' => true,
                ),
                'document' => array(
                    'label' => 'Documento',
                    'list' => true
                )
            ),
            'filters' => array(
                'name' => array(
                    'label'     => 'Nome',
                    'type'      => 'autocomplete',
                    'column'    => 'col-md-12'
                ),
                'email' => array(
                    'label'     => 'E-mail',
                    'type'      => 'texto',
                    'strategy'  => 'like', //exact
                    'column'    => 'col-md-12'
                ),
                'document' => array(
                    'label'     => 'Documento',
                    'type'      => 'custom',
                    'column'    => 'col-md-12',
                ),
                'active' => array(
                    'label'     => 'Ativo',
                    'type'      => 'custom',
                    'column'    => 'col-md-12',
                )
            )
        );
    }

    public function  indexAction($list = null)
    {
        $list = [];

        /**
         * @var \Register\Service\User $service
         */
        $service = $this->getServiceLocator()->get($this->service);
        $list = $service->canList($this->entity);

        return parent::indexAction($list); // TODO: Change the autogenerated stub
    }

    public function editAction($request = null)
    {
        $request = $this->getRequest();

        $redirect = null;

        if($request->isPost()){

            $data       = $request->getPost();
            $data_arr   = $data->toArray();

            $data->fromArray($data_arr);

            $request->setPost($data);

            if(isset($data['return_to']) && $data['return_to'] != ''){
                $redirect = $data['return_to'];
            }else{
                $redirect = $this->redirect()->toRoute('user/default', array(
                    'controller' => $this->controller,
                    'action' => $data_arr['action']
                ));
            }
        }

        return parent::editAction($request,null,$redirect); // TODO: Change the autogenerated stub
    }

    public function newAction($request = null)
    {
        $request = $this->getRequest();

        $db_login = $this->getEm()->getRepository('Register\Entity\User')->findOneById($this->getLogin());
        $redirect = null;
        if($request->isPost()){
            $data = $request->getPost();
            $data_arr = $data->toArray();
            $data_arr['document'] = $this->functions->soNumero($data_arr['document']);

            $data->fromArray($data_arr);

            $request->setPost($data);

            $redirect = $this->redirect()->toRoute('user/default',array(
                'controller' => $this->controller,
                'action' => $data_arr['action']
            ));

        }

        return parent::newAction($request,null,$redirect); // TODO: Change the autogenerated stub
    }

    public function viewAction()
    {
        return parent::viewAction(); // TODO: Change the autogenerated stub
    }

    public function userViewAction()
    {
        $em = $this->getEm();
        $repository = $em->getRepository($this->entity);
        $entity = $repository->find($this->params()->fromRoute('id',0));
        $id = $this->params()->fromRoute('id',0);
        $form = $this->getServiceLocator()->get($this->form);
        $form->setData((new Hydrator\ClassMethods())->extract($entity));

        /**
         * @var User $db_user
         */
        $db_user = $em->getRepository('Register\Entity\User')->findOneById($id);

        return new ViewModel(array(
            'db_user'   =>  $db_user,
            'form'      =>  $form
        ));
    }

    public function customerAction($list = null){
        $em = $this->getEm();

        $profile_key = "customer";
        $this->_listView['title'] = "Clientes";
        $this->_listView['controller'] = $profile_key;

        $allowed = $this->isAllow('Cliente','Visualizar');

        if($allowed){
            return parent::indexAction($list);
        }else{
            return $this->redirect()->toRoute('not-have-permission');
        }
    }

    public function profileAction(){
        $request = $this->getRequest();
        $em = $this->getEm();

        $db_user              = $em->getRepository('Register\Entity\User')->findOneById($this->params()->fromRoute('id'));
        $db_roles               = $em->getRepository('Acl\Entity\Role')->findAll();
        $db_user_roles     = $em->getRepository('Register\Entity\UserRole')->findBy(array('user'=>$db_user));

        if($request->isPost()){
            $post = $request->getPost()->toArray();

            foreach($db_user_roles as $db_user_role){
                $this->em->remove($db_user_role);
                $this->em->flush();
            }

            if(!empty($post['roles'])) {
                foreach ($post['roles'] as $role) {
                    $db_role = $em->getRepository('Acl\Entity\Role')->findOneById($role);

                    $db_user_role = new UserRole();

                    $db_user_role->setRole($db_role);
                    $db_user_role->setUser($db_user);

                    $this->em->persist($db_user_role);
                }

                $this->em->flush();
            }

            $this->flashmessenger()->addSuccessMessage("Registro salvo com sucesso!");
            return $this->redirect()->toRoute('user/default',array('controller'=>'user'));
        }

        $allowed = $this->isAllow($this->title,'Perfil');

        if($allowed){
            return new ViewModel(array(
                'db_user'            =>  $db_user,
                'db_roles'             =>  $db_roles,
                'db_user_roles'      =>  $db_user_roles
            ));
        }else{
            return $this->redirect()->toRoute('not-have-permission');
        }
    }

    public function activeAction(){
        /**
         * @var User $user
         */
        $user = $this->getEm()->getRepository('Register\Entity\User')->findOneById($this->params()->fromRoute('id'));
        $activateKey = $user->getActivationKey();
    
        $userService = $this->getServiceLocator()->get('Register\Service\User');

        $result = $userService->activate($activateKey);
        //Result quando tem o valor é um usuario
        if($result){
            $this->flashmessenger()->addSuccessMessage("Usuário ativado com sucesso!");
            return $this->redirect()->toRoute('user-auth');
    
        }else{
            $this->flashmessenger()->addErrorMessage("Houve um erro na ativação do usuário");
            return $this->redirect()->toRoute('user-auth');
        }
    }
    
    public function deactiveAction(){
        /**
         * @var User $user
         */
        $user = $this->getEm()->getRepository('Register\Entity\User')->findOneById($this->params()->fromRoute('id'));
        $user->setActive(null);
        $this->em->persist($user);
        $this->em->flush();
    
        $this->flashmessenger()->addMessage("Usuário foi desativado com sucesso!");
        return $this->redirect()->toRoute('admin/default',array('controller'=>'user'));
    }
}
