<div class="g-hidden-sm-down bg-green-light g-pa-20">
    <ul class="u-list-inline">
        <li class="list-inline-item g-mr-10">
            <a class="u-link-v5 g-color-white g-valign-middle" href="/admin-home">
                <i class="fa fa-dashboard"></i>&nbsp;&nbsp;Dashboard
            </a>
            <i class="hs-admin-angle-right g-font-size-12 g-color-white g-valign-middle g-ml-10"></i>
        </li>
        <li class="list-inline-item">
            <span class="g-valign-middle">
                <i class="hs-admin-desktop"></i>&nbsp;&nbsp;Painel de Pagamento
            </span>
        </li>
    </ul>
</div>
<?php
/**
 * @var \Solicitation\Entity\Solicitation $db_solicitation
 * @var \UserPlan\Entity\UserPlan $db_user_plan
 * @var \Account\Entity\Account $db_account
 * @var \Wallet\Entity\Wallet $db_wallet
 * @var \Register\Entity\User $db_user
 * @var \Cycle\Entity\Cycle[] $db_cycles
 */
$db_solicitation = $this->db_solicitation;
$db_user_plan   = $this->db_user_plan;
$db_account     = $this->db_account;
$db_wallet     = $this->db_wallet;
$db_user        = $this->db_user;
$db_cycles      = $this->db_cycles;

?>
<div ng-app="cash-out" ng-controller="CashOutController" class="col g-ml-45 g-ml-0--lg g-pb-65--md">
    <input type="hidden" id="type_solicitation" value="<?=$db_solicitation->getType()?>">
    <input type="hidden" id="user_plan_id" value="<?=$db_solicitation->getUserPlan()->getId()?>">
    <input type="hidden" id="user_id" value="<?=$db_solicitation->getUserPlan()->getUser()->getId()?>">
    <div class="g-pa-20">
        <div class="row">
            <div class="col-md-12 mb-4">
                <?php $this->getFlashMessenger();?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="g-pos-rel h-100 g-brd-around g-brd-gray-light-v7 g-rounded-4 g-pa-15 g-pa-30--md">
                    <header>
                        <h2>
                            <i class="hs-admin-money"></i>&nbsp;Painel de Pagamento
                        </h2>
                        <p>Faça o depósito bacário</p>
                    </header>
                    <hr class="d-flex g-brd-gray-light-v7 g-my-15 g-mt-25--md g-mb-30--md">
                    <div class="row g-mx-minus-10 g-mb-60">
                        <div class="col-md-6">
                            <div class="g-brd-around g-brd-gray-light-v7 g-rounded-4 g-pa-15 g-pa-20--md g-mb-30">
                                <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-black g-mb-20">
                                    <i class="hs-admin-user"></i>&nbsp;
                                    <?=$db_user->getName()?> - <?=$db_user->getDocument()?>
                                </h3>
                                <table class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Telefone</th>
                                            <th>Celular</th>
                                            <th>E-mail</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><?=$db_user->getPhone()?></td>
                                            <td><?=$db_user->getCelphone()?></td>
                                            <td><?=$db_user->getEmail()?></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="g-brd-around g-brd-gray-light-v7 g-rounded-4 g-pa-15 g-pa-20--md g-mb-30">
                                <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-black g-mb-20">
                                    <i class="hs-admin-thought"></i>&nbsp;Solicitação
                                </h3>
                                <table class="table table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>Solicitação</th>
                                        <th>Valor</th>
                                        <th>Forma de Pagamento</th>
                                        <th>Atendido?</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td><?=$db_solicitation->getTypeStr()?></td>
                                        <td><?=$db_solicitation->getValueStr()?></td>
                                        <td><?=$db_solicitation->getReceiveMethodStr()?></td>
                                        <td><?=$db_solicitation->getClosedStr()?></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <?php
                        if($db_account) {
                            ?>
                            <div class="col-md-12">
                                <div class="g-brd-around g-brd-gray-light-v7 g-rounded-4 g-pa-15 g-pa-20--md g-mb-30">
                                    <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-black g-mb-20">
                                        <i class="fa fa-bank"></i>&nbsp;Conta Bancária
                                    </h3>
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Banco</th>
                                            <th>Tipo de Conta</th>
                                            <th>Agência</th>
                                            <th>Conta</th>
                                            <th>Operação</th>
                                            <th>Titular</th>
                                            <th>Pessoa</th>
                                            <th>Documento</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td><?= $db_account->getBank() ?></td>
                                            <td><?= ($db_account->getType()) ? "Poupança" : "Corrente" ?></td>
                                            <td><?= $db_account->getAgency() ?></td>
                                            <td><?= $db_account->getAccountNumber() ?></td>
                                            <td><?= $db_account->getOperation() ?></td>
                                            <td><?= $db_account->getHolder() ?></td>
                                            <td><?= ($db_account->getTypeAccount()) ? "Jurídica" : "Física" ?></td>
                                            <td><?= $db_account->getCnpj() ?></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <?php
                        }

                        if($db_wallet){
                            ?>
                            <div class="col-md-12">
                                <div class="g-brd-around g-brd-gray-light-v7 g-rounded-4 g-pa-15 g-pa-20--md g-mb-30">
                                    <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-black g-mb-20">
                                        <i class="fa fa-bitcoin"></i>&nbsp;Carteira Bitcoin
                                    </h3>
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Nº da carteira</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td><?=$db_wallet->getAccount()?></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <?php
                        }
                        ?>

                        <div class="col-md-12">
                            <div class="g-brd-around g-brd-gray-light-v7 g-rounded-4 g-pa-15 g-pa-20--md g-mb-30">
                                <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-black g-mb-20">
                                    <i class="hs-admin-money"></i>&nbsp;Detalhes do Aporte
                                </h3>
                                <table class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Plano</th>
                                            <th>Valor</th>
                                            <th>Status</th>
                                            <th>Aprovado Em</th>
                                            <th>Vencimento Em</th>
                                            <th>Dias Restantes</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><?=$db_user_plan->getName()?></td>
                                            <td><?=$db_user_plan->getPlan()->getPriceStr()?></td>
                                            <td><?=$db_user_plan->getStatusStr()?></td>
                                            <td><?=$db_user_plan->getApprovedDateStr()?></td>
                                            <td class="g-color-red">
                                                <strong><?=$db_user_plan->getExpirationDateStr()?></strong>
                                            </td>
                                            <td class="g-color-red">
                                                <strong><?=$db_user_plan->getDaysRemainingStr()?></strong>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <hr />
                                <h4 class="h6 g-font-weight-600 g-color-black g-mb-20">
                                    Ações Disponíveis
                                </h4>
                                <div class="btn-group justified-content">
                                    <?php
                                    if($db_user_plan->getUser()->getId() == $db_user->getId())
                                    {
                                        ?>
                                        <label class="u-check">
                                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                   name="action"
                                                   type="radio"
                                                   ng-model="action"
                                                   value="0">
                                            <span class="btn btn-md btn-block u-btn-outline-lightgray g-color-white--checked g-bg-primary--checked rounded-0">
                                            Pagamento de Rendimento
                                        </span>
                                        </label>
                                        <label class="u-check">
                                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                   name="action"
                                                   type="radio"
                                                   ng-model="action"
                                                   value="1">
                                            <span class="btn btn-md btn-block u-btn-outline-lightgray g-color-white--checked g-bg-primary--checked g-brd-left-none--md rounded-0">
                                            Renovação de Contrato
                                        </span>
                                        </label>
                                        <label class="u-check">
                                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                   name="action"
                                                   type="radio"
                                                   ng-model="action"
                                                   value="2">
                                            <span class="btn btn-md btn-block u-btn-outline-lightgray g-color-white--checked g-bg-primary--checked g-brd-left-none--md rounded-0">
                                            Resgate Total
                                        </span>
                                        </label>
                                        <?php
                                    }else{
                                        ?>
                                        <label class="u-check">
                                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                   name="action"
                                                   type="radio"
                                                   ng-model="action"
                                                   value="3">
                                            <span class="btn btn-md btn-block u-btn-outline-lightgray g-color-white--checked g-bg-primary--checked g-brd-left-none--md rounded-0">
                                            Primeira Comissão
                                        </span>
                                        </label>
                                        <label class="u-check">
                                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                   name="action"
                                                   type="radio"
                                                   ng-model="action"
                                                   value="4">
                                            <span class="btn btn-md btn-block u-btn-outline-lightgray g-color-white--checked g-bg-primary--checked g-brd-left-none--md rounded-0">
                                            Comissão
                                        </span>
                                        </label>
                                        <?php
                                    }
                                    ?>
                                </div>
                                <hr />
                                <div class="row">
                                    <?php
                                    if($db_user_plan->getUser()->getId() == $db_user->getId()) {
                                        ?>
                                        <div ng-if="action == 0" class="col-md-12">
                                            <form method="post"
                                                  id="withdrawal"
                                                  name="withdrawal"
                                                  action="<?=$this->url('withdrawal');?>">
                                                <input type="hidden" name="solicitation_id" value="<?=$db_solicitation->getId()?>" >
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <label>Quantidade Solicitada</label>
                                                        <div class="form-group mb-0">
                                                            <div class="js-quantity input-group u-quantity--v2 g-brd-gray-light-v7 g-rounded-4">
                                                                <div class="input-group-addon d-flex justify-content-center align-items-center g-width-40 g-font-size-16 g-color-gray-light-v11 g-bg-gray-light-v8 rounded-0">
                                                                    <span>$</span>
                                                                </div>
                                                                <input type="text"
                                                                       name="price"
                                                                       class="form-control moeda form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-20 g-px-14 g-py-10"
                                                                       onkeypress="mascara(this,moeda)"
                                                                       form="withdrawal"
                                                                       required="required"
                                                                       value="<?=$db_solicitation->getValue()?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4 form-group">
                                                        <label>Ciclo Representante</label>
                                                        <select name="cycle" class="form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-px-14 g-py-10">
                                                            <option value="">Selecione...</option>
                                                            <?php
                                                            if(!empty($db_cycles)){
                                                                $count = 1;
                                                                foreach ($db_cycles as $db_cycle)
                                                                {
                                                                    ?>
                                                                    <option <?=($count == 1)?'selected':''?> value="<?=$db_cycle->getId()?>">
                                                                        <?=$db_cycle->getName()?>
                                                                    </option>
                                                                    <?php
                                                                    $count++;
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label>Solicitação Atendida?</label>
                                                        <div class="g-mb-15">
                                                            <label class="form-check-inline u-check g-pl-25 ml-0 g-mr-25">
                                                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                                       name="closed"
                                                                       type="radio"
                                                                       form="withdrawal"
                                                                       value="0">
                                                                <div class="u-check-icon-radio-v4 g-absolute-centered--y g-left-0 g-width-18 g-height-18">
                                                                    <i class="g-absolute-centered d-block g-width-10 g-height-10 g-bg-primary--checked"></i>
                                                                </div>
                                                                Não
                                                            </label>

                                                            <label class="form-check-inline u-check g-pl-25 ml-0 g-mr-25">
                                                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                                       name="closed"
                                                                       type="radio"
                                                                       form="withdrawal"
                                                                       checked
                                                                       value="1">
                                                                <div class="u-check-icon-radio-v4 g-absolute-centered--y g-left-0 g-width-18 g-height-18">
                                                                    <i class="g-absolute-centered d-block g-width-10 g-height-10 g-bg-primary--checked"></i>
                                                                </div>
                                                                Sim
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4 form-group">
                                                        <label>&nbsp;</label>
                                                        <button type="button"
                                                                form="withdrawal"
                                                                ng-click="decisionAction('withdrawal')"
                                                                class="btn btn-lg btn-primary g-bg-green form-control g-color-white">
                                                            <i class="fa fa-money"></i>&nbsp;Efetuar Pagamento
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <div ng-if="action == 1" class="col-md-12">
                                            <form method="post"
                                                  id="renew"
                                                  name="renew"
                                                  action="<?=$this->url('renew');?>">
                                                <input type="hidden" name="solicitation_id" value="<?=$db_solicitation->getId()?>" >
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <label>Quantidade Solicitada<br/>(Aporte + Rendimento)</label>
                                                        <h3 class="text-center g-color-green">
                                                            <?='R$ ' . number_format($db_solicitation->getUserPlan()->getPlan()->getPrice() + $db_solicitation->getValue(), 2, ',', '.')?>
                                                        </h3>
                                                    </div>
                                                    <div class="col-md-4 form-group">
                                                        <label>Ciclo Inicial</label>
                                                        <select name="cycle_start"
                                                                class="form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-px-14 g-py-10">
                                                            <option value="">Selecione...</option>
                                                            <?php
                                                            if(!empty($db_cycles)){
                                                                $count = 1;
                                                                foreach ($db_cycles as $db_cycle)
                                                                {
                                                                    ?>
                                                                    <option <?=($count == 1)?'selected':''?> value="<?=$db_cycle->getId()?>">
                                                                        <?=$db_cycle->getName()?>
                                                                    </option>
                                                                    <?php
                                                                    $count++;
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label>Solicitação Atendida?</label>
                                                        <div class="g-mb-15">
                                                            <label class="form-check-inline u-check g-pl-25 ml-0 g-mr-25">
                                                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                                       name="closed"
                                                                       type="radio"
                                                                       form="renew"
                                                                       value="0">
                                                                <div class="u-check-icon-radio-v4 g-absolute-centered--y g-left-0 g-width-18 g-height-18">
                                                                    <i class="g-absolute-centered d-block g-width-10 g-height-10 g-bg-primary--checked"></i>
                                                                </div>
                                                                Não
                                                            </label>

                                                            <label class="form-check-inline u-check g-pl-25 ml-0 g-mr-25">
                                                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                                       name="closed"
                                                                       type="radio"
                                                                       form="renew"
                                                                       checked
                                                                       value="1">
                                                                <div class="u-check-icon-radio-v4 g-absolute-centered--y g-left-0 g-width-18 g-height-18">
                                                                    <i class="g-absolute-centered d-block g-width-10 g-height-10 g-bg-primary--checked"></i>
                                                                </div>
                                                                Sim
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label>Comprovante</label>
                                                        <p>
                                                            Para abrir o comprovante clique
                                                            <a target="_blank" href="/uploads/<?=$db_user_plan->getReceipt()?>">aqui</a>
                                                        </p>
                                                    </div>
                                                    <div class="col-md-4 form-group">
                                                        <label>&nbsp;</label>
                                                        <button type="button"
                                                                form="renew"
                                                                ng-click="decisionAction('renew')"
                                                                class="btn btn-lg btn-primary g-bg-green form-control g-color-white">
                                                            <i class="fa fa-money"></i>&nbsp;Pagar e Renovar
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <div ng-if="action == 2" class="col-md-12">
                                            <form method="post"
                                                  id="rescue"
                                                  name="rescue"
                                                  action="<?=$this->url('rescue');?>">
                                                <input type="hidden" name="solicitation_id" value="<?=$db_solicitation->getId()?>" >
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <label>Quantidade Solicitada<br/>(Aporte + Rendimento)</label>
                                                        <h3 class="text-center g-color-green">
                                                            <?='R$ ' . number_format($db_solicitation->getUserPlan()->getPlan()->getPrice() + $db_solicitation->getValue(), 2, ',', '.')?>
                                                        </h3>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label>Solicitação Atendida?</label>
                                                        <div class="g-mb-15">
                                                            <label class="form-check-inline u-check g-pl-25 ml-0 g-mr-25">
                                                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                                       name="closed"
                                                                       type="radio"
                                                                       form="renew"
                                                                       value="0">
                                                                <div class="u-check-icon-radio-v4 g-absolute-centered--y g-left-0 g-width-18 g-height-18">
                                                                    <i class="g-absolute-centered d-block g-width-10 g-height-10 g-bg-primary--checked"></i>
                                                                </div>
                                                                Não
                                                            </label>

                                                            <label class="form-check-inline u-check g-pl-25 ml-0 g-mr-25">
                                                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                                       name="closed"
                                                                       type="radio"
                                                                       form="renew"
                                                                       checked
                                                                       value="1">
                                                                <div class="u-check-icon-radio-v4 g-absolute-centered--y g-left-0 g-width-18 g-height-18">
                                                                    <i class="g-absolute-centered d-block g-width-10 g-height-10 g-bg-primary--checked"></i>
                                                                </div>
                                                                Sim
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4 form-group">
                                                        <label>&nbsp;</label>
                                                        <button type="button"
                                                                form="rescue"
                                                                ng-click="decisionAction('rescue')"
                                                                class="btn btn-lg btn-primary g-bg-green form-control g-color-white">
                                                            <i class="fa fa-money"></i>&nbsp;Efetuar o Resgate
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <?php
                                    }else{
                                        ?>
                                        <div ng-if="action == 3" class="col-md-12">
                                            <form method="post"
                                                  id="withdrawal3"
                                                  name="withdrawal3"
                                                  action="<?=$this->url('withdrawal');?>">
                                                <input type="hidden" name="solicitation_id" value="<?=$db_solicitation->getId()?>" >
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <label>Quantidade Solicitada</label>
                                                        <div class="form-group mb-0">
                                                            <div class="js-quantity input-group u-quantity--v2 g-brd-gray-light-v7 g-rounded-4">
                                                                <div class="input-group-addon d-flex justify-content-center align-items-center g-width-40 g-font-size-16 g-color-gray-light-v11 g-bg-gray-light-v8 rounded-0">
                                                                    <span>$</span>
                                                                </div>
                                                                <input type="text"
                                                                       name="price"
                                                                       class="form-control moeda form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-20 g-px-14 g-py-10"
                                                                       onkeypress="mascara(this,moeda)"
                                                                       form="withdrawal3"
                                                                       required="required"
                                                                       value="<?=$db_solicitation->getValue()?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label>Solicitação Atendida?</label>
                                                        <div class="g-mb-15">
                                                            <label class="form-check-inline u-check g-pl-25 ml-0 g-mr-25">
                                                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                                       name="closed"
                                                                       type="radio"
                                                                       form="withdrawal3"
                                                                       <?=(!$db_solicitation->getClosed())?"checked":"";?>
                                                                       value="0">
                                                                <div class="u-check-icon-radio-v4 g-absolute-centered--y g-left-0 g-width-18 g-height-18">
                                                                    <i class="g-absolute-centered d-block g-width-10 g-height-10 g-bg-primary--checked"></i>
                                                                </div>
                                                                Não
                                                            </label>

                                                            <label class="form-check-inline u-check g-pl-25 ml-0 g-mr-25">
                                                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                                       name="closed"
                                                                       type="radio"
                                                                       form="withdrawal3"
                                                                       <?=($db_solicitation->getClosed())?"checked":"";?>
                                                                       value="1">
                                                                <div class="u-check-icon-radio-v4 g-absolute-centered--y g-left-0 g-width-18 g-height-18">
                                                                    <i class="g-absolute-centered d-block g-width-10 g-height-10 g-bg-primary--checked"></i>
                                                                </div>
                                                                Sim
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4 form-group">
                                                        <label>&nbsp;</label>
                                                        <button type="button"
                                                                form="withdrawal3"
                                                                ng-click="decisionAction('withdrawal3')"
                                                                class="btn btn-lg btn-primary g-bg-green form-control g-color-white">
                                                            <i class="fa fa-money"></i>&nbsp;Efetuar Pagamento
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <div ng-if="action == 4" class="col-md-12">
                                            <form method="post"
                                                  id="withdrawal4"
                                                  name="withdrawal4"
                                                  action="<?=$this->url('withdrawal');?>">
                                                <input type="hidden" name="solicitation_id" value="<?=$db_solicitation->getId()?>" >
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <label>Quantidade Solicitada</label>
                                                        <div class="form-group mb-0">
                                                            <div class="js-quantity input-group u-quantity--v2 g-brd-gray-light-v7 g-rounded-4">
                                                                <div class="input-group-addon d-flex justify-content-center align-items-center g-width-40 g-font-size-16 g-color-gray-light-v11 g-bg-gray-light-v8 rounded-0">
                                                                    <span>$</span>
                                                                </div>
                                                                <input type="text"
                                                                       name="price"
                                                                       class="form-control moeda form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-20 g-px-14 g-py-10"
                                                                       onkeypress="mascara(this,moeda)"
                                                                       form="withdrawal4"
                                                                       required="required"
                                                                       value="<?=$db_solicitation->getValue()?>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4 form-group">
                                                        <label>Ciclo Representante</label>
                                                        <select name="cycle"
                                                                class="form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-px-14 g-py-10">
                                                            <option value="">Selecione...</option>
                                                            <?php
                                                            if(!empty($db_cycles)){
                                                                $count = 1;
                                                                foreach ($db_cycles as $db_cycle)
                                                                {
                                                                    ?>
                                                                    <option <?=($count == 1)?'selected':''?> value="<?=$db_cycle->getId()?>">
                                                                        <?=$db_cycle->getName()?>
                                                                    </option>
                                                                    <?php
                                                                    $count++;
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label>Solicitação Atendida?</label>
                                                        <div class="g-mb-15">
                                                            <label class="form-check-inline u-check g-pl-25 ml-0 g-mr-25">
                                                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                                       name="closed"
                                                                       type="radio"
                                                                       form="withdrawal4"
                                                                       value="0">
                                                                <div class="u-check-icon-radio-v4 g-absolute-centered--y g-left-0 g-width-18 g-height-18">
                                                                    <i class="g-absolute-centered d-block g-width-10 g-height-10 g-bg-primary--checked"></i>
                                                                </div>
                                                                Não
                                                            </label>

                                                            <label class="form-check-inline u-check g-pl-25 ml-0 g-mr-25">
                                                                <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0"
                                                                       name="closed"
                                                                       type="radio"
                                                                       form="withdrawal4"
                                                                       checked
                                                                       value="1">
                                                                <div class="u-check-icon-radio-v4 g-absolute-centered--y g-left-0 g-width-18 g-height-18">
                                                                    <i class="g-absolute-centered d-block g-width-10 g-height-10 g-bg-primary--checked"></i>
                                                                </div>
                                                                Sim
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4 form-group">
                                                        <label>&nbsp;</label>
                                                        <button type="button"
                                                                form="withdrawal4"
                                                                ng-click="decisionAction('withdrawal4')"
                                                                class="btn btn-lg btn-primary g-bg-green form-control g-color-white">
                                                            <i class="fa fa-money"></i>&nbsp;Efetuar Pagamento
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="g-brd-around g-brd-gray-light-v7 g-rounded-4 g-pa-15 g-pa-20--md g-mb-30">
                                <h3 class="d-flex align-self-center text-uppercase g-font-size-12 g-font-size-default--md g-color-black g-mb-20">
                                    <i class="hs-admin-align-justify"></i>&nbsp;Últimas Transações
                                </h3>
                                <table class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Ciclo</th>
                                        <th>Categoria</th>
                                        <th>Data</th>
                                        <th>Tipo</th>
                                        <th>Valor</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr ng-class="{ 'g-color-red' : transaction.type,'g-color-green' : !transaction.type }"
                                        ng-repeat="transaction in transactions">
                                        <th>{{ getMonth(transaction._embedded.cycle.month) }}/{{ transaction._embedded.cycle.year }}</th>
                                        <th>{{ transaction._embedded.category_transaction.name }}</th>
                                        <th>{{ formatDate(transaction.date) }}</th>
                                        <th>{{ (transaction.type)?'Débito' : 'Crédito' }}</th>
                                        <th>R$ {{ transaction.value | currency:'':2:'pt-BR' }}</th>
                                    </tr>
                                    <tr ng-if="transactions.length >= 2">
                                        <td colspan="5">
                                            <p class="text-center">
                                                <a href="/admin/transaction?" target="_blank">Visualizar todas as transações</a>
                                            </p>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/assets/js/angular/cash-out.js" />
