<div class="g-hidden-sm-down bg-green-light g-pa-20">
    <ul class="u-list-inline">
        <li class="list-inline-item g-mr-10">
            <a class="u-link-v5 g-color-white g-valign-middle" href="/admin-home">
                <i class="fa fa-dashboard"></i>&nbsp;&nbsp;Dashboard
            </a>
            <i class="hs-admin-angle-right g-font-size-12 g-color-white g-valign-middle g-ml-10"></i>
        </li>
        <li class="list-inline-item">
            <span class="g-valign-middle">
                <i class="hs-admin-desktop"></i>&nbsp;&nbsp;Meus Investimentos
            </span>
        </li>
    </ul>
</div>
<div ng-app="panelInvestmentView" ng-controller="InvestimentViewController" class="col g-ml-0--lg g-pb-65--md">
    <div class="g-pa-20">
        <div class="row">
            <div class="col-md-12">
                <div class="g-pos-rel h-100 g-brd-around g-brd-gray-light-v7 g-rounded-4 g-pa-15 g-pa-30--md">
                    <header>
                        <h2>
                            <i class=""></i>&nbsp;Meus Investimentos
                        </h2>
                        <p>Gerencie seus investimentos</p>
                    </header>
                    <hr class="d-flex g-brd-gray-light-v7 g-my-15 g-mt-25--md g-mb-30--md">
                    <div class="row g-mx-minus-10 g-mb-60">
                        <div ng-repeat="user_plan in user_plans" class="col-md-6 col-lg-4 g-mb-30">
                            <div class="card h-100 g-brd-gray-light-v7 rounded">
                                <header class="card-header g-bg-transparent g-brd-bottom-none g-pa-20 g-pa-30--sm">
                                    <div class="media g-mb-15">
                                        <div class="d-flex align-self-center">
                                            Plano {{ user_plan._embedded.plan.name }}
                                        </div>

                                        <div class="media-body d-flex justify-content-end">
                                            <div class="g-pos-rel g-z-index-2">
                                                <a id="dropDown1Invoker"
                                                   class="u-link-v5 g-line-height-0 g-font-size-24 g-color-gray-light-v6 g-color-secondary--hover"
                                                   href="#"
                                                   aria-controls="dropDown1"
                                                   aria-haspopup="true"
                                                   aria-expanded="false"
                                                   data-dropdown-event="click"
                                                   data-dropdown-target="#dropDown{{ user_plan.id }}"
                                                   data-dropdown-type="jquery-slide">
                                                    <i class="hs-admin-more-alt g-ml-20"></i>
                                                </a>
                                                <div id="dropDown{{ user_plan.id }}"
                                                     class="u-shadow-v31 g-pos-abs g-right-0 g-z-index-2 g-bg-white u-dropdown--css-animation u-dropdown--hidden u-dropdown--reverse-y u-dropdown--jquery-slide"
                                                     aria-labelledby="dropDown1Invoker"
                                                     style="display: none;">
                                                    <ul class="list-unstyled g-nowrap mb-0">
                                                        <li>
                                                            <a ng-click="viewExtract(user_plan.id)"
                                                               data-toggle="modal"
                                                               data-target="#modal_extract"
                                                               class="d-flex align-items-center u-link-v5 g-bg-gray-light-v8--hover g-font-size-12 g-font-size-default--md g-color-gray-dark-v6 g-px-25 g-py-14"
                                                               href="#">
                                                                <i class="hs-admin-layout-list-thumb-alt g-font-size-18 g-color-gray-light-v6 g-mr-10 g-mr-15--md"></i>
                                                                Visualizar Extrato
                                                            </a>
                                                        </li>
                                                        <li>
                                                            <a ng-click="viewCashOut(user_plan)"
                                                               class="d-flex align-items-center u-link-v5 g-bg-gray-light-v8--hover g-font-size-12 g-font-size-default--md g-color-gray-dark-v6 g-px-25 g-py-14"
                                                               href="#">
                                                                <i class="hs-admin-money g-font-size-18 g-color-gray-light-v6 g-mr-10 g-mr-15--md"></i>
                                                                Solicitar Saque
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <h3 ng-class="{ 'g-color-green' : user_plan.balance > 0 }" class="g-font-weight-300 g-font-size-40 g-color-black g-mb-15">
                                        <strong>R$ {{ user_plan.balance  | currency:'':2:'pt-BR'}}</strong>
                                    </h3>
                                    <span class="{{ getStatusColor(user_plan.status) }} u-tags-v1 text-center g-brd-around  g-color-white g-rounded-50 g-py-4 g-px-15">
                                        {{ (cycleFuture(user_plan._embedded.first_cycle))?"Início em " + getMonth(user_plan._embedded.first_cycle.month) :getStatus(user_plan.status) }}
                                    </span>
                                    <br />

                                </header>

                                <hr class="d-flex g-brd-gray-light-v7 g-mx-20 g-mx-30--sm my-0">

                                <div class="card-block g-pa-20">
                                    <h4 class="media g-font-weight-300 g-font-size-16 g-mb-10 g-mb-20--md">
                                        <span class="d-flex align-self-center g-color-gray-dark-v6 g-font-weight-400">
                                            Dias para expirar o aporte
                                        </span>
                                        <span class="media-body align-self-center text-right g-font-size-18--md g-color-black">
                                            {{ getExpirationDays(user_plan.approved_date) }}
                                        </span>
                                    </h4>

                                    <div class="progress g-height-6 g-rounded-3 g-mb-10 g-mb-15--md">
                                        <div class="progress-bar g-bg-lightblue-v3 g-rounded-3" role="progressbar" style="width: {{ getPercentDays(user_plan.approved_date) }}%" aria-valuenow="{{ getPercentDays(user_plan.approved_date) }}" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div ng-if="user_plans.length == 0">
                            <h2 class="alert alert-danger text-center pt-4">
                                <i class="hs-admin-face-sad g-font-size-60"></i><br />Você não possui nenhum aporte, não perca oportunidade, faça seu primeiro investimento!<br />
                                <a class="btn btn-xl g-brd-around g-rounded-50 u-btn-gradient-v1 g-font-size-30 mt-5 mb-4"
                                   href="<?=$this->url('panel-investiment')?>">
                                    <i class="hs-admin-money"></i>&nbsp;Investir
                                </a>
                            </h2>
                        </div>
                        <?=$this->partial('partials/modal-extract');?>
                        <?=$this->partial('partials/modal-cash_out');?>
                        <?=$this->partial('partials/modal-select-account');?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?=$this->partial('partials/modal-investiment');?>
</div>
<script src="/assets/js/angular/panel-investiment.js" />
