<div class="row">
    <div class="col-md-4 col-md-offset-8">
        <div class="card">
            <div class="header">
                <div class="row">
                    <div class="col-md-12">
                        <h4 style="margin: 0"><i class="pe-7s-search"></i>&nbsp;Filtro</h4>
                    </div>
                </div>
            </div>
            <div class="content">
                <form method="post" name="filter-form" action="">
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label>Nome</label>
                            <input name="user_name" id="inputUserName" class="form-control" value="<?= $_POST['user_name'] ?>">
                            <input type="hidden" name="user" id="inputUser" value="<?= $_POST['user'] ?>">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <button class="btn btn-success" >Filtrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
<?php

/**
 * @var \Register\Entity\User[] $db_users
 * @var \Register\Entity\User $db_login
 */
$functions = new \Base\Controller\BaseFunctions();
$db_login = $this->UserIdentity('User');
$db_users = $this->em->getRepository('Register\Entity\User')->findByCompany($db_login->getCompany());
$names = array();
foreach($db_users as $db_user){
    $names[] = array('label' => $functions->formatarTexto($db_user->getName()),'value' =>$db_user->getId());
}
$names = json_encode($names);

?>
<script>
    $(document).ready(function(){
        <?php
        if(isset($names) && $names != '')
        {
            ?>
            let Json = '<?=$names?>';
            var users = JSON.parse(Json);

            $("#inputUserName").autocomplete({
                source: users,
                open: function (event, ui) {
                    $('#inputUser').val('');
                },
                select: function(event, ui) {
                    $('#inputUserName').val(ui.item.label);
                    $('#inputUser').val(ui.item.value);
                    return false;
                }
            }).blur(function(){
                if($("#inputUserName").val() == '')
                {
                    $("#inputUserName").val('');
                    $('#inputUser').val('');
                }

                if($('#inputUser').val() == '')
                {
                    $("#inputUserName").val('');
                }
            });
            <?php
        }
        ?>
    });
</script>
