<?php
/**
 * @var DoctrineModule\Form\Element\ObjectSelect $element
 * @var \Base\Controller\BaseFunctions $functions
 */
$element = $this->element;
$element->setAttribute('name',$element->getName());
$functions = new \Base\Controller\BaseFunctions();

if($element instanceof \DoctrineModule\Form\Element\ObjectSelect){
    $target_class   = $element->getOption('target_class');
    $find_method    = $element->getOption('find_method');
    $property       = $element->getOption('property');
    $db_entities    = array();
    $getMethod = 'get'.$functions->toCamelCase($property,true);

    if(isset($find_method['name'])){

        if(!empty($find_method['params'])){
            $find_method['name'] = 'findAll';
            $findName = $find_method['name'];
            $db_entities = $this->getEm()->getRepository($target_class)->$find_method['name']($find_method['params']);
        }else{
            $find_method['name'] = 'findAll';
            $findName = $find_method['name'];
            $db_entities = $this->getEm()->getRepository($target_class)->$findName();
        }

    }else{
        $db_entities = $this->getEm()->getRepository($target_class)->findAll();
    }

    $values = array();

    $count = 1;
    $limit = -1;
    if(!empty($db_entities))
    {
        foreach($db_entities as $db_entity)
        {
            $values[] = array(
                'label'     =>  $functions->formatarTexto($db_entity->$getMethod()),
                'value'     =>  $db_entity->getId()
            );

            if($limit != -1 && $count == $limit){
                break;
            }

            $count++;
        }
    }

    $values = json_encode($values);

    ?>
    <script>
        $(document).ready(function(){
            <?php
            if(isset($values) && $values != '')
            {
            ?>
            let Json = '<?=$values?>';
            var values = JSON.parse(Json);

            $("#input<?=$element->getName()?>Label").autocomplete({
                source: values,
                messages: {
                    noResults: function () {
                        $("#input<?=$element->getName()?>Label").val('');
                    },
                    results: function() {}
                },
                open: function (event, ui) {
                    $('#input<?=$element->getName()?>').val('');
                },
                select: function(event, ui) {
                    $("#input<?=$element->getName()?>Label").val(ui.item.label);
                    $("input[id=input<?=$element->getName()?>]").val(ui.item.value).trigger("input");

                    return false;
                }
            }).blur(function(){
                if($("#input<?=$element->getName()?>Label").val() == '') {
                    $("#input<?=$element->getName()?>Label").val('');
                    $("input[id=input<?=$element->getName()?>]").val('');
                }
            });
            <?php
            }
            ?>
        });
    </script>
    <?php
    $db_entity = null;
    if($element->getValue()){
        $db_entity = $this->getEm()->getRepository($target_class)->findOneById($element->getValue());
    }

    ?>
    <div class="g-pos-rel">
        <span class="g-pos-abs g-top-0 g-right-0 d-block g-width-40 h-100 opacity-0 g-opacity-1--success">
            <i class="hs-admin-check g-absolute-centered g-font-size-default g-color-secondary"></i>
        </span>
        <input id="input<?=$element->getName()?>Label" class="form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-20 g-px-14 g-py-10"
               value="<?=($db_entity)?$db_entity->$getMethod():'';?>"
            <?=($element->getAttribute('required'))?'required':''?>>
    </div>


    <input type="hidden" name="<?=$element->getName()?>" id="input<?=$element->getName()?>" value="<?=$element->getValue()?>">
    <?php
}else{
    ?>
    <p class="text-center">
        Campo auto complete com erro
    </p>
    <?php
}

?>
